### ISSUE TITLE
The desktop file is lacking a Categories= entry

### ISSUE THREAD

**Issue by probonopd** [vaibhavpandeyvpz/apkstudio#104]
The desktop file is lacking a `Categories=` entry in the `*.desktop` file.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, please add at least one of the following in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

__electron-builder offers native support for this since [v19.22.1](https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1).__. Please see the `category` key at https://www.electron.build/configuration/linux-other.

References:
* https://github.com/AppImage/AppImageHub/issues/2
* https://travis-ci.org/AppImage/appimage.github.io/builds/356531856#L582
* https://github.com/AppImage/appimage.github.io/pull/458

**Comment by Surendrajat** [comment]
Thanks for you kind attention.
I've updated the AppImage file.

**Comment by probonopd** [comment]
Thanks, re-running the test at https://github.com/AppImage/appimage.github.io/pull/458.

**Comment by Surendrajat** [comment]
Still failing **EXPLORING DATA** step.
Any idea what I'm missing here? 
`+dv database/ImageMagick/imagemagick.desktop --yaml -o database/ImageMagick/desktop.yaml`
Can It be possibly avoided like many other successful builds?

**Comment by probonopd** [comment]
I am a bit puzzled what is going on here myself. It seems that `dv` has issues converting this desktop files into the yaml format, but I can't see an obvious reason why.

As a side note, I think `Terminal=true` is wrong since your application seems to be GUI and not a CLI tool.

**Comment by Surendrajat** [comment]
Thanks. That was a mistake. `Terminal=true` is removed now. Could you please test now?

**Comment by probonopd** [comment]
Thanks, triggered.

**Comment by Surendrajat** [comment]
The screenshot doesn't seem very cool though :)
I'm not sure how does it work but could you update it with one from [here](https://github.com/vaibhavpandeyvpz/apkstudio/blob/master/external/screenshots/apkstudio881.png)?

**Comment by probonopd** [comment]
Yes, strange, I need to investigate. In the meantime, if you ship AppStream metadata, it will be used. http://output.jsbin.com/qoqukof

**Comment by Surendrajat** [comment]
Done! Hope it'll be alright now.

**Comment by vaibhavpandeyvpz** [comment]
Closing this as no updates from anyone.
