### ISSUE TITLE
Icon/Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [vaibhavpandeyvpz/apkstudio#109]
If the project needs logo, I am willing to give my best design for this. Thanks PO !

**Comment by Surendrajat** [comment]
Well. Why not. As you can see we already have [this logo](https://raw.githubusercontent.com/vaibhavpandeyvpz/apkstudio/master/res/icons/apkstudio.ico) for APK Studio designed by @vaibhavpandeyvpz. However you're welcome to update [icons](https://github.com/vaibhavpandeyvpz/apkstudio/tree/master/res/icons).

**Comment by loydjayme25** [comment]
you already have a outstanding logo.
