### ISSUE TITLE
Building stuck

### ISSUE THREAD

**Issue by martinmagic** [vaibhavpandeyvpz/apkstudio#11]
lrelease: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/lrelease': No such file or directory

this is the error i get after lrelease resources/lang/en.ts

any ideas

**Comment by vaibhavpandeyvpz** [comment]
@martinmagic Please use QT5 (5.4+), QT4 is not supported.

**Comment by martinmagic** [comment]
now i get this 

g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o ide.o sources/ide.cpp
In file included from sources/adb.h:5:0,
                 from sources/consoledock.h:6,
                 from sources/adbdock.h:4,
                 from sources/ide.cpp:9:
sources/process.h:4:30: fatal error: QRegularExpression: No such file or directory

how do i open software

**Comment by vaibhavpandeyvpz** [comment]
Please post contents of your **/home/martin/apkstudio/apkstudio.pro** file to a [Gist](http://gist.github.com/) and link it here.

**Comment by martinmagic** [comment]
https://gist.github.com/martinmagic/a8c4135580eec57bd113

**Comment by vaibhavpandeyvpz** [comment]
and the output of your ```qmake --version```?

**Comment by martinmagic** [comment]
qmake --version
QMake version 2.01a
Using Qt version 4.8.6 in /usr/lib/x86_64-linux-gnu

**Comment by vaibhavpandeyvpz** [comment]
As you can see in the output, it is pointing to the default qt4 installation. Can you install qt5 from [this](https://github.com/vaibhavpandeyvpz/apkstudio/blob/master/.travis.yml#L7) ppa and proceed with install?

**Comment by martinmagic** [comment]
i receive this 

sudo apt-get -qq update
W: Failed to fetch http://ppa.launchpad.net/beineri/opt-qt55/ubuntu/dists/vivid/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/beineri/opt-qt55/ubuntu/dists/vivid/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by vaibhavpandeyvpz** [comment]
Then your best bet would be to go for Qt suite from [here](http://www.qt.io/download-open-source/#section-2). That ain't going to fail I strongly believe.

**Comment by martinmagic** [comment]
installed but still gives off
qmake apkstudio.pro CONFIG+=release
WARNING: /home/martin/apkstudio/apkstudio.pro:60: Unescaped backslashes are deprecated.

checked qmake --version

still says

QMake version 2.01a
Using Qt version 4.8.6 in /usr/lib/x86_64-linux-gnu

**Comment by vaibhavpandeyvpz** [comment]
Forget command-line in the case, just open up QT Creator an File > Open Project the *.pro file. It will use the bundled version for sure.

**Comment by martinmagic** [comment]
thanks it worked 100%

**Comment by rodrigograca31** [comment]
Two notes for future reference:
1. There are builds already compiled/built... Because of the design of the page I didn't noticed that and compiled my own copy and lost at least 3 hours....
2. I solved the above erro with: `sudo apt-get install qttools5-dev-tools`
