### ISSUE TITLE
How to Install in Mac ?

### ISSUE THREAD

**Issue by nitinsindhubt** [vaibhavpandeyvpz/apkstudio#111]

**Comment by Surendrajat** [comment]
I don't own a Mac. But you can compile it on your own. Check the wiki.

**Comment by luispereira** [comment]
I' also having problems configuring the qt for this project in Mac, if anyone could help me I would be glad

**Comment by ScubaInstructor** [comment]
I built apkstudio from source against qt 5.12. The UI doesn't really look slick.
But I am wondering where adb & zipaling need to be installed an the Mac for apkstudio to find it. Any suggestions?

**Comment by vaibhavpandeyvpz** [comment]
@nitinsindhubt I now have built a **.dmg** for **Mac OS X** which you can just mount and run **APK Studio** from it.
