### ISSUE TITLE
Unable open file from assets folder

### ISSUE THREAD

**Issue by sephuxeresh** [vaibhavpandeyvpz/apkstudio#112]
I am unable to open the file from assets folder - after I've decompiled the apk.

**Comment by Surendrajat** [comment]
Well. That depends what kind of files do you have in assets folder. ApkStudio supports common image formats but for other assets like mp3 etc. you'll need to open those in external apps.

**Comment by sephuxeresh** [comment]
Does it mean I cannot open txt file? How about to add right context menu "Open with..." and show default dialog with list common programs associated with that kind of file's type?

**Comment by Surendrajat** [comment]
That's right but I'll fix that soon.
About context menu option, let me see how it's done in Qt then only I can implement it.

**Comment by sephuxeresh** [comment]
Thank You.
How about this solution https://stackoverflow.com/a/23581037/619673 
It is about  to invoke Open Dialog With from terminal's command. The disadvantage is that you can only use this for Windows.

**Comment by Surendrajat** [comment]
I intent to do something similar ([this](https://doc.qt.io/qt-5/qdesktopservices.html#openUrl)).
