### ISSUE TITLE
Uninstaller

### ISSUE THREAD

**Issue by RicoHeat** [vaibhavpandeyvpz/apkstudio#113]
Tried everything to uninstall the program from Windows 7 but nothing seems to work.. I tried reinstalling it and then uninstallling again but it fails everytime.

**Comment by Surendrajat** [comment]
Are you using latest version of ApkStudio? If yes, it doesn't require installing as it's a portable version. You just need to extract and run it. If you wanna remove it, simply delete the extracted files.

**Comment by RicoHeat** [comment]
Yes this portable version is very nice.. The version I'm stuck with is d49d3de.. Honestly now that I think about it I cant even remember where I downloaded from. The 'About' link brought me here today so I was hoping to get lucky and find a solution.. I really dont want to delete this older version I have manually.

**Comment by Surendrajat** [comment]
Well. As far I can remember the older version had an uninstaller in same folder as apkstudio executable. Maybe you still can find it. Otherwise just delete the dir along with `%userdir%\.apkstudio\vendor` if you want.

**Comment by RicoHeat** [comment]
Well my friend.. I visited https://bintray.com/vaibhavpandeyvpz/generic/apkstudio/view  
I redownloaded it again.. I still cannot get the uninstaller to complete the task.

**Comment by Surendrajat** [comment]
I don't think why you can't just delete the entire dir instead. Anyways, the installer should've created an `Uninstaller.exe` somewhere as you can see [here](https://github.com/brbsix/apkstudio/blob/5cfab3905e04bc358981a3a7b38f9374d1a6b55c/apkstudio.xml#L44) and [here](https://github.com/brbsix/apkstudio/blob/5cfab3905e04bc358981a3a7b38f9374d1a6b55c/apkstudio.xml#L49).
