### ISSUE TITLE
Decompiling source dex file

### ISSUE THREAD

**Issue by abforce** [vaibhavpandeyvpz/apkstudio#114]
Currently APK studio can disassemble dex files, however it could be nice to have the ability to decompile the dex files. i.e. dex2jar and then jar to java.

Another feature request: dark theme.

**Comment by vaibhavpandeyvpz** [comment]
@abforce It took too much time but it's here now. Java sources & dark theme.

**Comment by gMan1990** [comment]
@vaibhavpandeyvpz where is `decompile the dex files`?
