### ISSUE TITLE
apktool framework installed on different location

### ISSUE THREAD

**Issue by ewwink** [vaibhavpandeyvpz/apkstudio#115]
using command line, apktool 2.3

    C:\Users\<user>\AppData\Local\apktool\framework

APK Studio select from

    C:\Users\<user>\apktool\framework

OS: Windows 7

**Comment by jonhnyng** [comment]
how we can change the apk studio select framework, so they can match together....i think i have this problem that why i can't rebuild the apk file....they say warning and something about framework

**Comment by vaibhavpandeyvpz** [comment]
This issue belongs to an older version.
