### ISSUE TITLE
can rebuild the apk file after edited

### ISSUE THREAD

**Issue by jonhnyng** [vaibhavpandeyvpz/apkstudio#117]
I got this problem anyone can help me? please T.T 

S: WARNING: Could not write to (C:\Users\Jonhny\AppData\Local\apktool\framework), using C:\Users\Jonhny\AppData\Local\Temp\ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
W: C:\Users\Jonhny\Desktop\translate tool\vdck_mod\res\values\strings.xml:9: error: Error parsing XML: not well-formed (invalid token)
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Jonhny\AppData\Local\Temp\brut_util_Jar_5991012340151890244.tmp, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 19, --version-code, 11

**Comment by Surendrajat** [comment]
Check the `C:\Users\Jonhny\Desktop\translate tool\vdck_mod\res\values\strings.xml` file, you must've missed some tag or so. If not then head over to [apktool repo](https://github.com/iBotPeaches/Apktool) and search for similar issues.
