### ISSUE TITLE
APKStudio doesn't recognize .apk in file browser

### ISSUE THREAD

**Issue by tama10111** [vaibhavpandeyvpz/apkstudio#119]
When I want to open an apk file, it doesn't appear in the file browser. I have to search manually my apk file, then it's listed. I'm on Debian 9, I use GNOME Shell 3.22.3, and I just built APKStudio

**Comment by cptwilson** [comment]
I'm having this same issue with build compiling from master at commit [0cb7d7d](https://github.com/vaibhavpandeyvpz/apkstudio/commit/0cb7d7d76c5facf4c48c100be2adf23ccb888b5b) on Arch Linux x86_64, GCC 8.2.1, and Qt 5.12.2. The AppImage provided on the Releases page, however, works properly.

**Comment by vaibhavpandeyvpz** [comment]
Might be as issue with **Qt** versions on those distros. I have checked with [Stephen's](https://launchpad.net/~beineri) & official **Qt** releases, it works fine.

**Comment by vaibhavpandeyvpz** [comment]
Closing this as no response thus assuming new build should've fixed. Feel free to re-open in case it doesn't.
