### ISSUE TITLE
Font color bug on macOS with dark mode

### ISSUE THREAD

**Issue by donglua** [vaibhavpandeyvpz/apkstudio#121]
![image](https://user-images.githubusercontent.com/3875265/47410011-08a71000-d797-11e8-998f-417470892cdc.png)

**Comment by onestoreindia** [comment]
@donglua You may now use the provided macOS image [here](https://github.com/vaibhavpandeyvpz/apkstudio/releases/latest) and use *dark theme* in **APK Studio > Settings > Appearance** to fix this.

**Comment by vaibhavpandeyvpz** [comment]
@donglua You may now use the provided macOS image here and use dark theme in APK Studio > Settings > Appearance to fix this.
