### ISSUE TITLE
brut.androlib.AndrolibException: brut.common.BrutException: could not exec: 

### ISSUE THREAD

**Issue by nikhilgeo** [vaibhavpandeyvpz/apkstudio#122]
I installed the latest apkstudio - apkstudio-v4.0.3-windows_x86
apktool apktool_2.3.4.jar
uber-apk-signer-1.0.0.jar

I hit the issue when I rebuild the apk after modifying the AndroidManifest.xml

```
$ java -Xmx256m -jar C:/Users/user1/.apkstudio/vendor/apktool.jar -f b C:/Users/user1/Documents/t1/CL/t2/apkstudio -o C:/Users/user1/Documents/t1/CL/t2/apkstudio.apk
I: Using Apktool 2.3.4
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Building resources...
S: WARNING: Could not write to (C:\Users\user1\AppData\Local\apktool\framework), using C:\Users\user1~1\AppData\Local\Temp\ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
brut.androlib.AndrolibException: brut.common.BrutException: could not exec:
```

Any ideas how to resolve this ?

**Comment by nikhilgeo** [comment]
I belive it's an issue with apktool https://github.com/iBotPeaches/Apktool/issues/1376
The recommendation is to use apktool with -r, how can it be tied with the apkstudio ?

**Comment by Surendrajat** [comment]
**`-r`** switch is same as **`Decode Resources`** checkbox in apk selection dialog. Just uncheck it.
BTW you have left out the actual error logs from console.

**Comment by vaibhavpandeyvpz** [comment]
As @nikhilgeo pointed out, this seems to be an issue with [apktool#1376](https://github.com/iBotPeaches/Apktool/issues/1376). Please follow there.

**Comment by rmvz3** [comment]
> **`-r`** switch is same as **`Decode Resources`** checkbox in apk selection dialog. Just uncheck it.

Is that checkbox been removed in the last 5.1.0 release? I still get this error with that (using Apktool 2.4.0)

**Comment by vaibhavpandeyvpz** [comment]
Oh, yes! I will add it some time today. Thanks for notifying.

**Comment by vaibhavpandeyvpz** [comment]
@rmvz3 I have added the options in [5.2.0](https://github.com/vaibhavpandeyvpz/apkstudio/releases/tag/5.2.0) release.

**Comment by rmvz3** [comment]
> @rmvz3 I have added the options in [5.2.0](https://github.com/vaibhavpandeyvpz/apkstudio/releases/tag/5.2.0) release.

OMG That was FAST!! Thank you!
