### ISSUE TITLE
No linux release and how to make one ?

### ISSUE THREAD

**Issue by mcitew** [vaibhavpandeyvpz/apkstudio#128]
Sorry for basic question.

In the release, a few packages found but there is no linux binary ?

From the source, also don't know how to compile.

Please help.

**Comment by vaibhavpandeyvpz** [comment]
The ***.AppImage** files on the [Releases](https://github.com/vaibhavpandeyvpz/apkstudio/releases) page are meant for linux systems only. You may please use those.
