### ISSUE TITLE
Files disappeared from desktop after decompile

### ISSUE THREAD

**Issue by nobody122** [vaibhavpandeyvpz/apkstudio#129]
Hey, 

I've tried to decompiled on .apk, by mistake I set Desktop as a project path, and after click "Decode" 80% of my files on desktop just disappeared, like .mp4, .txt, shortcuts etc. I'm not sure why it happen. I tried to recover them by using "Recuva" software but didn't help. 

Here is console log:  https://pastebin.com/81W5z0tA

**Comment by vaibhavpandeyvpz** [comment]
Oh, that's the [apktool](https://github.com/ibotpeaches/apktool.git)'s `-f` flag doing it. 😬
