### ISSUE TITLE
INSTALL_PARSE_FAILED_NO_CERTIFICATES

### ISSUE THREAD

**Issue by pemgithub** [vaibhavpandeyvpz/apkstudio#130]
I ran APK Studio and it created 1.apk in C:\Users\[user]\AppData\Local\Temp.  Next I did:

>adb install -r 1.apk
Performing Streamed Install
adb: failed to install 1.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1714834550.tmp/base.apk: Attempt to get length of null array]

**Comment by vaibhavpandeyvpz** [comment]
You need to sign the built APK as well.

**Comment by pemgithub** [comment]
Does APK Studio sign it for me?  Note Settings > Signing is blank

**Comment by pemgithub** [comment]
I don't see this option.  APK Studio decompiled base.apk to "base.apk-decompiled" folder.  Then when I did Project > Build, it appears to have generated 1.apk to C:\Users\[user]\AppData\Local\Temp.
![image](https://user-images.githubusercontent.com/13956322/59487586-0aab0580-8e32-11e9-939a-a1d53ccb29af.png)

**Comment by pemgithub** [comment]
Well I tried this: C:\Programs\Java\jdk-12.0.1\bin\keytool.exe -genkey -v -keystore my-release-key.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000
Then copy 1.apk into base.apk-decompiled folder so that APK Studio can see it, so I can right-click to sign.
However, adb install 1.apk now gives a different error: 

>adb install C:\PemCode\base.apk-decompiled\1.apk
Performing Streamed Install
adb: failed to install C:\PemCode\base.apk-decompiled\1.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]

I uninstalled the app from Android, so the error seems wrong

**Comment by vaibhavpandeyvpz** [comment]
Clearing phone caches (from recovery) should help for sure.

**Comment by pemgithub** [comment]
thank you, I was able to get it to work, though I guess a lot of games seem to break if you modify the APK (all I did was set debug mode to true)
