### ISSUE TITLE
Feature request: compiling per file based java code into smali

### ISSUE THREAD

**Issue by mcitew** [vaibhavpandeyvpz/apkstudio#131]
Is it at possible to integrate a compilation of per file java code into sample smali files ? 

We know the conversion from apk to java source is not always 100% successful. So it will be good to be able to incorporate a per file java code compilation into smali files, so that we can cross reference the generated smali files with the original decompiled smali files, and then incorporate the necessary changes.

**Comment by vaibhavpandeyvpz** [comment]
That would’ve been possible but lastly I found it’s nearly impossible to provide all classpath dependencies while compiling that java file into smali.

Only way could be to transpile instead of compile java to smali but that isn’t easy either.

**Comment by mcitew** [comment]
I am unable to comment on whether which is the right approach but from usability point of view, but I hope you could see that this will be an extremely useful feature if we want to add a onKeyListener() or any other java code.
