### ISSUE TITLE
its crashing on windows 10 x64 ( at least it feels like that)

### ISSUE THREAD

**Issue by Askmewho** [vaibhavpandeyvpz/apkstudio#132]
hi! ive download the release and the deps from the app source links and suddenly the app dindt turn on again. it doesnt run any more. dont know how to debug it on windows.

**Comment by vaibhavpandeyvpz** [comment]
Can you remove all binaries you downloaded and try opening again. I doubt it's crashing when resolving dependencies versions.

**Comment by Askmewho** [comment]
Sorry, I cant right now. Thanks!
