### ISSUE TITLE
Program closes on startup without message

### ISSUE THREAD

**Issue by gonzol** [vaibhavpandeyvpz/apkstudio#133]
Hello. I'm using version 5.2 and Jadx 1.0.0
When program has not set yet Jadx bat file it asks for it, so I set "C:\Program Files (x86)\Jadx\bin\jadx-gui.bat." Then program runs fine and opens Jadx GUI on decompile. But when I close Apk Studio and try to reopen it it simply closes without any message. Deleting Jadx bat path from registry solves the problem, but I need to set it again after program start. When set "jadx.bat" instead of "jadx-gui.bat" the program starts fine, but Jadx GUI doesn't open on decompile.
I tried "jadx-gui-1.0.0-with-jre-windows" but with no success.
I also tried very old Jadx 0.6.0 with setting "jadx-gui.bat" and with this version program works fine and doesn't close on startup. 
I use Java jre1.8.0_212 64bit and Windows 7 x64
Any solution?

**Comment by vaibhavpandeyvpz** [comment]
You have to point it to `jadx.bat` (command line, not GUI).
