### ISSUE TITLE
Can see the file/folder view tree on the left anymore

### ISSUE THREAD

**Issue by TheSecurityDev** [vaibhavpandeyvpz/apkstudio#137]
I closed the tree view, and now I can't seem to open it again. I've tried everything I can think of except reinstalling. I want to be able to find the files in the tree, but I can no longer do so. Is this a bug, or what am I missing?

**Comment by vaibhavpandeyvpz** [comment]
You can just right-click on the toolbar and it will show you options to hide/show dockable items.
