### ISSUE TITLE
I deleted the other tabs now only Manifest is showing

### ISSUE THREAD

**Issue by Regioxys** [vaibhavpandeyvpz/apkstudio#139]
i accidentally deleted files and project tab and i don't know how to get them back nor did i find any solutions regarding this issue
![image](https://user-images.githubusercontent.com/53794331/62488448-1f7a9880-b7e6-11e9-9cb4-9fb7b49eac2a.png)

**Comment by xamix** [comment]
Same issue for me, where are stored settings in order to get back other tab?

**Comment by Regioxys** [comment]
As far as I know. I don't think there are any settings to restore the tabs

**Comment by xamix** [comment]
Found it, right click on the border just below the settings icon and select the deactivated tab

**Comment by Regioxys** [comment]
Thanks

**Comment by xamix** [comment]
Seem that after this I connot Sign/Export or Install, it seem it loose binary path in settings even if they seem present.
