### ISSUE TITLE
Jadx

### ISSUE THREAD

**Issue by palaboy** [vaibhavpandeyvpz/apkstudio#140]
The jadx cannot read the jadx.bat
![apk studio error1](https://user-images.githubusercontent.com/2505495/62828701-6241d380-bc1f-11e9-82bb-11694532096d.png)
![apk studio error2](https://user-images.githubusercontent.com/2505495/62828692-227aec00-bc1f-11e9-8e5d-9d0a7ce8ead2.png)

**Comment by vaibhavpandeyvpz** [comment]
Jadx requires JAVA_HOME to be set before you run it.

**Comment by palaboy** [comment]
Thanks for reply bro i see the error the java home
