### ISSUE TITLE
after first run, it wont run again.

### ISSUE THREAD

**Issue by booali** [vaibhavpandeyvpz/apkstudio#141]
I'm on windows 10.

**Comment by fenixfx** [comment]
Same problem here

**Comment by Dhanamerdeka** [comment]
same problem :(

**Comment by Dhanamerdeka** [comment]
windows 10 64bit

**Comment by fenixfx** [comment]
UPD
Try to kill adb.exe in process explorer

**Comment by Dhanamerdeka** [comment]
> UPD
> Try to kill adb.exe in process explorer

not work
in me adb.exe not running....
the program won't open anymore after first run
when open it only black little window and closed automatically

**Comment by fenixfx** [comment]
Did you try to run it with admin?

> > UPD
> > Try to kill adb.exe in process explorer
> 
> not work
> in me adb.exe not running....
> the program won't open anymore after first run
> when open it only black little window and closed automatically

Did you try to run it with admin?

**Comment by Dhanamerdeka** [comment]
> Did you try to run it with admin?
> 
> > > UPD
> > > Try to kill adb.exe in process explorer
> > 
> > 
> > not work
> > in me adb.exe not running....
> > the program won't open anymore after first run
> > when open it only black little window and closed automatically
> 
> Did you try to run it with admin?

when i have a error
i try all way to fix that by myself
Reinstall, Run with/without admin.. and clear temp file
AND NOT WORK
if you say pls try disable antivirus or anything like that I TRY ALL POSSIBLE WAY AND STILL NOT WORK

**Comment by sonbui00** [comment]
Same problem here

**Comment by sonbui00** [comment]
My issue is from jadx. I change jadx folder name and open APKStudio again

**Comment by Surendrajat** [comment]
@booali @Dhanamerdeka @fenixfx @sonbui00 try opening it from `cmd` by issuing a command `.\apkstudio.exe` that way it might give some logs in `cmd`. Otherwise, just clone the source and use `qtcreator` to check what's going wrong.

**Comment by vaibhavpandeyvpz** [comment]
To be able to run *jadx*, you must specify `JAVA_HOME` environment variable as well otherwise it reportedly creates trouble.
