### ISSUE TITLE
Open Folder not actually opening folder structure?

### ISSUE THREAD

**Issue by AxDSan** [vaibhavpandeyvpz/apkstudio#145]
![](https://i.imgur.com/QAB8fiD.png)

Left nagivation bar, for the folder structure only shows AndroidManifest, not the entire app folder structure? Is this supposed to happen?

**Comment by vaibhavpandeyvpz** [comment]
This may be due to a failed decompilation or the apk you were decompiling did not have `classes.dex` file (system apps).

**Comment by bubblesofdeath** [comment]
then how do i open the folder tree again?

**Comment by gabyavra** [comment]
I have closed the inner windows as well and I don't find how to reopen them (in order to view the console, folder tree and so on)

<img width="620" alt="image" src="https://user-images.githubusercontent.com/11969114/69829180-b05b0100-1227-11ea-89c3-b213a8b2c1da.png">

**Comment by gabyavra** [comment]
Found it in old closed bugs. right-click on the left bar and select what you need

<img width="660" alt="image" src="https://user-images.githubusercontent.com/11969114/69829554-1eec8e80-1229-11ea-90b7-99a2f2b70e1e.png">

**Comment by gabyavra** [comment]
> ![](https://camo.githubusercontent.com/7a0c29e6403e77faecb8e576bcc4961851d13f72/68747470733a2f2f692e696d6775722e636f6d2f514142386669442e706e67)
> 
> Left nagivation bar, for the folder structure only shows AndroidManifest, not the entire app folder structure? Is this supposed to happen?

see up

**Comment by AxDSan** [comment]
![](https://i.imgur.com/RHMYYi5.png)

Thanks everyone!
