### ISSUE TITLE
Error while installing in ubuntu

### ISSUE THREAD

**Issue by pramodwadkar** [vaibhavpandeyvpz/apkstudio#146]
apkstudio/QHexView/QHexView.pri
Qt-Frameless-Window-DarkStyle/DarkStyle.cpp
Qt-Frameless-Window-DarkStyle/darkstyle.qrc
Qt-Frameless-Window-DarkStyle/DarkStyle.h

Above files are missing

**Comment by vaibhavpandeyvpz** [comment]
You have clone and update git submodules as well.
