### ISSUE TITLE
Cannot start anymore after changing Java path to another

### ISSUE THREAD

**Issue by MLXProjects** [vaibhavpandeyvpz/apkstudio#147]
Hi! I have some java versions installed (1.5, 1.7 & 1.8) because I need to work with some old SDKs.
I've tried to open ApkStudio and changed the settings to use the java.exe from jre_1.8.x path instead of the autodetected one, restarted the program and the next error has been thrown: 
![image](https://user-images.githubusercontent.com/40145907/68062160-6265e280-fce7-11e9-9c27-c449bc34fb59.png)
I can't even find the settings file (if ApkStudio has anyone) to change that.
How can I change that back to another path? (deleting the ApkStudio folder and extracting it again doesn't work).

**Comment by vaibhavpandeyvpz** [comment]
On Windows (as I guess from screenshot), the settings can be changed or reset by using **regedit** for `Computer\HKEY_CURRENT_USER\Software\Vaibhav Pandey\APK Studio`.
