### ISSUE TITLE
After the first start ApkStudio doesn't open anymore and crashes with Qt5Core.dll error 0xc0000005

### ISSUE THREAD

**Issue by AndreaFar** [vaibhavpandeyvpz/apkstudio#149]
The first time I have opened Apk Studio, It has shown config window. I have set path parameters and used It, this was the first and last time It worked, because It continuously crash at the start, no error message no splash screen, just an immediate crash after the launch of ApkStudio.exe.

On windows log I see that program fails to open due to Qt5Core.dll error 0xc0000005

ApkStudio 5.2.0 x64 
OS: Windows 10 x64

**Comment by arseniy899** [comment]
I can confirm - after first successful launch, it doesn't start any more completely.
Reinstall, moreover - installation of another version, doesn't help either.

**Comment by Jagadeeshrian** [comment]
Yes, even i face the same problem.

**Comment by Jagadeeshrian** [comment]
> I can confirm - after first successful launch, it doesn't start any more completely.
> Reinstall, moreover - installation of another version, doesn't help either.

Just try deleting the jadx (path) and opening apk studio again.

**Comment by nightcap79** [comment]
Jagadeeshrian is correct, you need to change the folder name of (jadx) or delete it, before opening Apkstudio !!!!

**Comment by Directory** [comment]
for me, it seems like the issue was sorta solved by instead just downloading the minimal jadx zip `https://github.com/skylot/jadx/releases/download/v1.1.0/jadx-1.1.0.zip` and selecting the nongui bat

**Comment by solocop** [comment]
> for me, it seems like the issue was sorta solved by instead just downloading the minimal jadx zip `https://github.com/skylot/jadx/releases/download/v1.1.0/jadx-1.1.0.zip` and selecting the nongui bat

you're right. Please remove jadx folder and open apk studio again. In the setting screen. Please choose non-gui bat.
