### ISSUE TITLE
Unescaped backslashes are deprecated and can't compile it

### ISSUE THREAD

**Issue by GildedHonour** [vaibhavpandeyvpz/apkstudio#15]
Errors on Ubuntu 14.04:

```
# 1
alex@blackanbook:apkstudio$ lrelease res/lang/en.ts
Updating 'res/lang/en.qm'...
    Generated 117 translation(s) (117 finished and 0 unfinished)


# 2
alex@blackanbook:apkstudio$ qmake apkstudio.pro CONFIG+=release
WARNING: /home/alex/Documents/projects/var/apkstudio/apkstudio.pro:58: Unescaped backslashes are deprecated.

# 3
alex@blackanbook:apkstudio$ make
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o adb.o src/adb.cpp
In file included from ./include/adb.h:5:0,
                 from src/adb.cpp:1:
./include/process.h:4:30: fatal error: QRegularExpression: No such file or directory
 #include <QRegularExpression>
                              ^
compilation terminated.
make: *** [adb.o] Error 1


```

**Comment by vaibhavpandeyvpz** [comment]
[APK Studio](https://github.com/vaibhavpandeyvpz/apkstudio) requires [Qt5](http://www.qt.io/download-open-source/), you are building it against **Qt4**

**Comment by GildedHonour** [comment]
I have Qt5 installed.

**Comment by vaibhavpandeyvpz** [comment]
But I can see it's not in path. How you installed it?

**Comment by GildedHonour** [comment]
qt5 manually, and qt4 by "sudo apt-get install qt4-qtconfig libqt4-dev"

**Comment by vaibhavpandeyvpz** [comment]
With **manually**, do you mean download it from *Digia*'s website or compiling from source? If you downloaded the *Digia*'s binary installer, you can then follow [this](https://github.com/vaibhavpandeyvpz/apkstudio/wiki/Building) guide to build [APK Studio](https://github.com/vaibhavpandeyvpz/apkstudio) from source.

**Comment by GildedHonour** [comment]
downloading from Qt's website. thanks, I'll try.

**Comment by samkpo** [comment]
I don't think yout still with the same trouble, but this might help. Try installing qt5-default.

**Comment by ptx0** [comment]
on gentoo linux,

```
/usr/lib64/qt5/bin/qmake apkstudio.pro CONFIG+=release
```
