### ISSUE TITLE
Add menu bar option to open/close windows

### ISSUE THREAD

**Issue by 2three8** [vaibhavpandeyvpz/apkstudio#150]
On Mac OS.
I closed all windows and there is no left bar to get them back.
I tried uninstalling and removing plist files, and reinstalling but it did not revert.

Is there another way to restore the windows?

Possibly a screenshot is here...

<img width="1035" alt="Screen Shot 2019-11-29 at 22 22 12" src="https://user-images.githubusercontent.com/42092800/69891835-59bcf800-12f7-11ea-97a7-9f195e6a337a.png">

**Comment by mbryantramirez** [comment]
This state also seems to persist, You can delete the app completely and purge all files from libraries and caches and when you download the app again it will open the app in this state again. The problem persists on all older versions of the app too.

**Comment by 2three8** [comment]
Hi. I managed to clear all the files to start afresh.
directory: ..../Application SavedState had a file 'test.apkstudio.SavedState'
directory: /private/var/db/ ... something had a 'test.apkstudio ???' file
I booted to safe mode, which can clear some cache etc in Mac, so I think this cleared the /private/var ... file.
I deleted the other.

There is no uninstall function (in MacOS) which would remove related files, so clearing up was tricky.

I think test.apkstudio may be an error.  The Info.plist inside the apkstudio.app /Contents   :

       <key>CFBundleIdentifier</key>
	<string>test.apkstudio</string>

Re the problem I first noted, enabling/disabling the tabs works as long as at least one tab is open - with zero tabs there is no control area to re-enable any tab (ie, the title bar of the tab and the dock area itself)

**Comment by romangromov** [comment]
Same problem on Windows 10: just installed APK Studio, then accidentally closed Console window as well as project structure window, now it looks like:
![image](https://user-images.githubusercontent.com/1655573/71321225-911e5f00-24c7-11ea-85be-356cf7afcc9d.png)

and NO WAY to re-open Console and Project Structure - can not find any option or even config file - there are no any config files for APK Studio in it's directory... please help to re-open or re-install, Thanks!

**Comment by Surendrajat** [comment]
@romangromov Right click on the menu bar to bring those back. Took a while to figure that out :)

**Comment by romangromov** [comment]
@Surendrajat wow, thanks a lot!

**Comment by harveyslash** [comment]
on macOS, I am still unable to get any windows back. this tool is unusable. after deleting those files I still have the same persistent state :(
