### ISSUE TITLE
Unable to get APK

### ISSUE THREAD

**Issue by a2zwebtech** [vaibhavpandeyvpz/apkstudio#151]
Hi!
After build project, I am not getting apk file. my log is like this

$ C:\ProgramData\Oracle\Java\javapath\java.exe -Xmx256m -jar C:\Windows\apktool.jar b C:\Users\Maitri\Downloads\com.myapp_2019-09-23.apk-decompiled
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
Process exited with code 0.

Please help me for solve it.
Thanks!

**Comment by Surendrajat** [comment]
Check in **`C:\Users\Maitri\Downloads\com.myapp_2019-09-23.apk-decompiled\dist\`**

**Comment by siwhele** [comment]
i have same problem ..  ware i can find my recompile  APK file?please help me

**Comment by Surendrajat** [comment]
@vaibhavpandeyvpz It's better to point the dir structure out in README.

**Comment by vaibhavpandeyvpz** [comment]
Indeed! In some time.

**Comment by siwhele** [comment]
$ C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe -Xmx300m -jar C:\Users\janaka\Desktop\ApkStudio-5.0.0-x64\APKTOOL\apktool.jar b C:\Users\janaka\Desktop\APK EDIT\ppp.apk-decompiled
I: Using Apktool 2.3.4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
Process exited with code 0.
![Untitled-1](https://user-images.githubusercontent.com/58837301/70798875-2043bc80-1dce-11ea-9451-2ca5eb777f8c.png)
**please Help Me** ware can see my build apk?  

My  Opareting system is  windows 7  64 bit
i used ApkStudio-5.0.0-x64  now
i gate letast version but same problem ...

**Comment by vaibhavpandeyvpz** [comment]
That’s is dist folder.
