### ISSUE TITLE
Application wont run after first run

### ISSUE THREAD

**Issue by GauthamAsir** [vaibhavpandeyvpz/apkstudio#156]
I opened the application and setup the paths for 3rd part libraries and i accidently closed it, now its not opening again tried older version too 
versions i tried 5.2.0, 5.1.0 windows 64bit
my os Windows 10 64bit

**Comment by nht10** [comment]
Try to delete all files and folders (apk studio, apktool.jar, uber-sign.....) then restart your PC and download everything again. And make sure you choose right files for setting. That is how I fix it when I face same problem.

**Comment by GauthamAsir** [comment]
> Try to delete all files and folders (apk studio, apktool.jar, uber-sign.....) then restart your PC and download everything again. And make sure you choose right files for setting. That is how I fix it when I face same problem.

I tried it but still the same

**Comment by nht10** [comment]
Delete every things again. Then re-download all of theme again. But this time, before you open it, try to move all the folders, files to an other location (Directory). If this trick still can't help you, maybe you should try to reinstall Windows. Or try to use Apk studio on a Virtual Machine, or VPS.

**Comment by vaibhavpandeyvpz** [comment]
@GauthamAsir Similar problem usually occurs when `JAVA_HOME` is not set before setting `jadx`. You try either removing `jadx` folder or setting `JAVA_HOME` environment variable to your **JDK** directory before running apkstudio.

**Comment by GauthamAsir** [comment]
> Delete every things again. Then re-download all of theme again. But this time, before you open it, try to move all the folders, files to an other location (Directory). If this trick still can't help you, maybe you should try to reinstall Windows. Or try to use Apk studio on a Virtual Machine, or VPS.

This didnt worked, anyway thanks for replying

**Comment by GauthamAsir** [comment]
> @GauthamAsir Similar problem usually occurs when `JAVA_HOME` is not set before setting `jadx` path. You may try either removing `jadx` folder or setting `JAVA_HOME` environment variable to your **JDK** directory before running apkstudio.

Thanks, it worked
