### ISSUE TITLE
APK Studio doesn't work correctly with latest Java versions

### ISSUE THREAD

**Issue by AndreaFar** [vaibhavpandeyvpz/apkstudio#159]
If you try to set the path of `java.exe`  APK Studio seems unable to use it and it asks to set the path again when you relaunch it. 

I have tried with Java 14 and Windows 10 x64

**Comment by vaibhavpandeyvpz** [comment]
Can you please share output of `java -version` from command line?

**Comment by AndreaFar** [comment]
> Can you please share output of `java -version` from command line?

java version "14" 2020-03-17
Java(TM) SE Runtime Environment (build 14+36-1461)
Java HotSpot(TM) 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)
