### ISSUE TITLE
OS X Installation / Support

### ISSUE THREAD

**Issue by ethicalhack3r** [vaibhavpandeyvpz/apkstudio#16]
Has anyone successfully installed apkstudio on OS X?

**Comment by vaibhavpandeyvpz** [comment]
I do not have a **Mac**, but I believe you can easily build [APK Studio](https://github.com/vaibhavpandeyvpz/apkstudio) on **Mac** as long you follow [this](https://github.com/vaibhavpandeyvpz/apkstudio/wiki/Building) guide & download the **Mac** Qt version from [here](http://download.qt.io/official_releases/qt/5.5/5.5.1/qt-opensource-mac-x64-clang-5.5.1.dmg).

**Comment by ethicalhack3r** [comment]
Awesome! I'll give that a try, thanks!

**Comment by sovanyio** [comment]
Don't mean to bring this back up but can confirm this works (I'm on the sierra preview) so maybe this should be added to README / installation instructions / etc?

**Comment by tjunxiang92** [comment]
Tried on El Capitan and it worked. One extra step is to download apktool.jar and place it into /Users/{username}/.apkstudio/vendor

**Comment by huttarl** [comment]
@sovanyio Are you confirming, or asking someone else to confirm, that this works on the sierra preview?

**Comment by tjunxiang92** [comment]
@huttarl That's strange. Worked for me following the steps on El Capitan Version 10.11.6.

**Comment by huttarl** [comment]
@tjunxiang92 I was able to get it to work eventually. I created a [new issue](https://github.com/vaibhavpandeyvpz/apkstudio/issues/66) to describe the problems I encountered.

**Comment by IvoPereira** [comment]
I've faced the exact same problems @huttarl found.

Any updates on this? Have you been able to go on with it @huttarl?

**Comment by eleddie** [comment]
Any updates?
