### ISSUE TITLE
Apkstudio as web service 

### ISSUE THREAD

**Issue by DivekJohns** [vaibhavpandeyvpz/apkstudio#161]
Its been very hard to find an updated and maintained tool like apk studio,
It would be nice if we have it online ?

**Comment by vaibhavpandeyvpz** [comment]
There is https://deapk.vaibhavpandey.com/ but it does not support recompiling as of yet.

**Comment by Surendrajat** [comment]
@DivekJohns I'm implementing apk studio functionalities in a [VS Code extension](https://github.com/Surendrajat/APKLab). You can download it and easily install it on [GitPod online IDE](https://www.gitpod.io/).

**Comment by DivekJohns** [comment]
> There is https://deapk.vaibhavpandey.com/ but it does not support recompiling as of yet.

Hmm! Anything I can help out!

**Comment by vaibhavpandeyvpz** [comment]
You can absolutely can. But the thing why I refrained from making it recompile as well were server resources. Rebuilding would require bigger servers and that means bigger costs.

**Comment by DivekJohns** [comment]
> @DivekJohns I'm implementing apk studio functionalities in a [VS Code extension](https://github.com/Surendrajat/APKLab). You can download it and easily install it on [GitPod online IDE](https://www.gitpod.io/).

Sounds Good, I would be glad if anything needs to be done

**Comment by DivekJohns** [comment]
> You can absolutely can. But the thing why I refrained from making it recompile as well were server resources. Rebuilding would require bigger servers and that means bigger costs.
> […](#)
> Sent from my iPhone
> On 01-Jun-2020, at 7:37 AM, Divek John ***@***.***> wrote: ﻿ There is https://deapk.vaibhavpandey.com/ but it does not support recompiling as of yet. Hmm! Anything I can help out! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

What will be the minimum system requirements for recompiling?

**Comment by Surendrajat** [comment]
>Sounds Good, I would be glad if anything needs to be done

@DivekJohns You can help with testing as I update it every weekend. I've opened issues for missing features if you want to help with that. Simple refactoring is also welcome.

>What will be the minimum system requirements for recompiling?

Not a lot but it depends on the app actually. I think @vaibhavpandeyvpz meant that continuously running an online service with such resources will be costly.

**Comment by vaibhavpandeyvpz** [comment]
@Surendrajat Yes, indeed. I refrain from building synchronous web-apps. In my server matrix, it would involve an API only backend, a big-enough worker for apps of any size (on separate sandbox machine), push(er), object storage and SPA frontend. I have no recent plans for it but am deeply interested.

**Comment by vaibhavpandeyvpz** [comment]
Closing this as https://deapk.vaibhavpandey.com/ is already there and @Surendrajat is maintaining a cloud compatible VS Code extension.
