### ISSUE TITLE
Folders not being opened

### ISSUE THREAD

**Issue by TaquitoSlayer** [vaibhavpandeyvpz/apkstudio#162]
Whenever I try and open a folder rather than an APK, it just keeps going inside the subdirectory instead of just opening said folder.

I'm on Mac OS 10.14.6
Java 8 Update 251.

**Comment by vaibhavpandeyvpz** [comment]
To open a folder, you have to choose the `apktool.yml` file.

**Comment by TaquitoSlayer** [comment]
Thanks!
