### ISSUE TITLE
Changes inside .java will not get compiled into apk

### ISSUE THREAD

**Issue by 0x416c69** [vaibhavpandeyvpz/apkstudio#164]
Is the feature even implemented? It's simple though.

**Comment by Surendrajat** [comment]
Of course, it won't. Java source is generated for reference only and can not be recompiled. You need to modify `.smali` files.

**Comment by yejong2013** [comment]
smaili file is very complicate
it is no way to recompile the apk that changed the java file in apk studio?

**Comment by Surendrajat** [comment]
@yejong2013 Try [DexPatcher](https://forum.xda-developers.com/android/software/tool-dexpatcher-modify-android-dex-apk-t3060854).
