### ISSUE TITLE
Can't sign, export or install apk

### ISSUE THREAD

**Issue by CrayzyOne** [vaibhavpandeyvpz/apkstudio#169]
As the title says i cannot sign, export or install any apk because the options for that are greyed out.
I don't find out why.

Anyone who can tell my issue?

greetings

**Comment by RubixSolver99** [comment]
Same for me

**Comment by joelzabsonre** [comment]
you can just try to do it manually by the parameter button. It's work for me.

**Comment by RubixSolver99** [comment]
Where is the parameter button at? I'm having trouble understanding what you mean...

**Comment by RubixSolver99** [comment]
@joelzabsonre Is there any chance you could help me find the parameter button? I am really trying to figure out how to sign this apk.

**Comment by vaibhavpandeyvpz** [comment]
You need to choose the built APK in the project tree on left to enable these options.
