### ISSUE TITLE
can't build successfully and I just follow the instruction

### ISSUE THREAD

**Issue by yifeilyf** [vaibhavpandeyvpz/apkstudio#17]
![issue1](https://cloud.githubusercontent.com/assets/12167107/10687564/9c8c9130-79a0-11e5-8ec6-7bf99d75815b.png)
This is the error that I follow the instruction.

![issue2](https://cloud.githubusercontent.com/assets/12167107/10687576/adfdd5dc-79a0-11e5-8af1-f8c891f7d9b3.png)
This is the error that I build by qt creator.

Anyone could help to fix that?
Many thanks.

**Comment by yifeilyf** [comment]
the second picture is that I follow the instruction inside the apk studio folder.
![issue3](https://cloud.githubusercontent.com/assets/12167107/10687725/def05704-79a1-11e5-9b54-573819668829.png)

**Comment by vaibhavpandeyvpz** [comment]
What's your Qt version & GCC version? I see compiler does not support *lambda* & *function pointers*.

**Comment by yifeilyf** [comment]
![image](https://cloud.githubusercontent.com/assets/12167107/10708370/4e98bb46-7a38-11e5-9e79-21c7a8a1de1a.png)

**Comment by vaibhavpandeyvpz** [comment]
It needs **Qt** *5.4*+.

**Comment by yifeilyf** [comment]
I just installed qt 5.5 and when I run the program, the main window does not show and return these errors on terminal. And I use Ubuntu on Virtualbox.
![image](https://cloud.githubusercontent.com/assets/12167107/10710118/8dca3daa-7a7c-11e5-93e8-a2929bfb2ff3.png)

**Comment by vaibhavpandeyvpz** [comment]
**VirtualBox** does not seem to support OpenGL 3.0 that well. Try turning off 3d Acceleration in your VM settings.

**Comment by yifeilyf** [comment]
I try to close the 3D, the Qt could open, but still have errors.
![image](https://cloud.githubusercontent.com/assets/12167107/10714462/0321902c-7b2b-11e5-8b19-a66b31d1cb44.png)

I download the Qt offline installer.

**Comment by yifeilyf** [comment]
This is what I follow the instruction.
![image](https://cloud.githubusercontent.com/assets/12167107/10714470/802a06ee-7b2b-11e5-8d51-2fe9f9eb35aa.png)

**Comment by yifeilyf** [comment]
I download the Qt from here
![image](https://cloud.githubusercontent.com/assets/12167107/10714475/ca2cc88a-7b2b-11e5-8d38-524fc84737e8.png)

**Comment by yifeilyf** [comment]
I try the example and it is successful
![image](https://cloud.githubusercontent.com/assets/12167107/10714511/776faa0c-7b2d-11e5-91c6-d446f0b9f71c.png)

**Comment by vaibhavpandeyvpz** [comment]
Indeed you have downloaded the latest **Qt**, but the command-line has references to the older **Qt** version. Try uninstalling the older installation you installed via **Software Center**. And use the latest install only.

**Comment by yifeilyf** [comment]
I think I already delete the old version, how could I know what the version I use at the moment?

**Comment by yifeilyf** [comment]
should I detele everything and install again? what command should i use to completely uninstall?

**Comment by vaibhavpandeyvpz** [comment]
**<package-name>** = package from which you installed the **Qt Creator** earlier (the earlier one, not one from Qt Website)

```bash
sudo apt-get remove <package-name>
```

**Comment by yifeilyf** [comment]
I think I already uninstalled the old version before, still could not build

**Comment by vaibhavpandeyvpz** [comment]
The last I could help with is: you got [Teamviewer](https://www.teamviewer.com/hi/index.aspx)?

**Comment by yifeilyf** [comment]
![image](https://cloud.githubusercontent.com/assets/12167107/10714722/4cf8708e-7b36-11e5-8f1d-91dd4ca15291.png)

**Comment by yifeilyf** [comment]
![image](https://cloud.githubusercontent.com/assets/12167107/10714723/77a98caa-7b36-11e5-96ac-b3298d6180aa.png)

**Comment by yifeilyf** [comment]
can not connect?

**Comment by vaibhavpandeyvpz** [comment]
nah, it's stuck on authenticating everytime. You installed on *Guest* or *Host*?

**Comment by yifeilyf** [comment]
![image](https://cloud.githubusercontent.com/assets/12167107/10714755/0e3ac9f8-7b38-11e5-99aa-44148a8a7772.png)

**Comment by vaibhavpandeyvpz** [comment]
Go with **Basic** & **Personal**.

**Comment by yifeilyf** [comment]
try again
![image](https://cloud.githubusercontent.com/assets/12167107/10714765/5abc4dd8-7b38-11e5-9f7c-a8e451c64f2d.png)

**Comment by vaibhavpandeyvpz** [comment]
maybe it's not connecting linux -> windows. wait for me, botting up my windows laptop.

**Comment by yifeilyf** [comment]
again there is dialog that show

**Comment by yifeilyf** [comment]
I could click trust

**Comment by vaibhavpandeyvpz** [comment]
You are not good to go. :+1:

**Comment by yifeilyf** [comment]
Thank you so much, save my life!!!

**Comment by yifeilyf** [comment]
when I use it to decompile it by using a 123.apk. there is nothing on the project 123 folder?
![image](https://cloud.githubusercontent.com/assets/12167107/10714908/012147f0-7b3e-11e5-80db-5307a4a05f7d.png)

**Comment by vaibhavpandeyvpz** [comment]
maybe you need to install device specific framework if this app makes use of any system resources

**Comment by yifeilyf** [comment]
Do you know where could I download the framework?

**Comment by vaibhavpandeyvpz** [comment]
You need to pull from the device. It could be available else where on Internet, but pulling one from device is quicker in my opinion.

**Comment by yifeilyf** [comment]
thank you
