### ISSUE TITLE
Rebuild apk failed

### ISSUE THREAD

**Issue by liangxiwei** [vaibhavpandeyvpz/apkstudio#173]
some apk use [AndResGuard](https://github.com/shwenzhang/AndResGuard) project , It changes res/drawable/png to r/d/a. 
But the apkstudio can't rebuild it.

Can you fix it, please.

**Comment by Surendrajat** [comment]
apkstudio doesn't rebuild an apk by itself, it uses [Apktool](https://github.com/iBotPeaches/Apktool) under the hood. So better open the issue there.
