### ISSUE TITLE
Where does the built apk file go?

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [vaibhavpandeyvpz/apkstudio#182]
I edited an apk, then I clicked build, but now I can't find where the built apk file is. Can someone please tell me (and please say where it goes in the readme)

**Comment by Surendrajat** [comment]
in `dist` dir.

**Comment by ego-lay-atman-bay** [comment]
oh, uh, I've actually already found out. I've also started using just the commandline with apktool. What I didn't know was how to actually sign the apk in order to install it, but I've also figured it out.

**Comment by Surendrajat** [comment]
Cool. Seems like it can be documented. Do you think adding a [gif](https://github.com/APKLab/APKLab/raw/master/assets/rebuild.gif) like this helps?

**Comment by ego-lay-atman-bay** [comment]
well, I actually followed this tutorial https://www.wikihow.com/Edit-APK-Files

**Comment by Surendrajat** [comment]
Got it. Maybe you can close this issue now?

**Comment by ego-lay-atman-bay** [comment]
yeah, I was thinking of that
