### ISSUE TITLE
set up on windows 10

### ISSUE THREAD

**Issue by yifeilyf** [vaibhavpandeyvpz/apkstudio#19]
I install apk studio on windows, first time open it. 
![image](https://cloud.githubusercontent.com/assets/12167107/10777791/1a00c3f4-7d5a-11e5-9a1e-e19372e9e224.png)

Then I set Vendor path 
![image](https://cloud.githubusercontent.com/assets/12167107/10777807/3c3cab68-7d5a-11e5-88be-0a8010eb0034.png)

after that, I try to decompile a apk, but there is nothing
![image](https://cloud.githubusercontent.com/assets/12167107/10777822/55f5dbe2-7d5a-11e5-8106-98723d65cf57.png)

Any help?
Many thanks.

**Comment by yifeilyf** [comment]
GCC version is 4.8.1, there is no QT.

**Comment by vaibhavpandeyvpz** [comment]
you need to install device framework

**Comment by yifeilyf** [comment]
could u send a link to me, im not sure which version I need to use?

**Comment by vaibhavpandeyvpz** [comment]
it depends on which apk, from which rom you are decompiling. you need to pull it from device.
