### ISSUE TITLE
Not useful

### ISSUE THREAD

**Issue by Elmue** [vaibhavpandeyvpz/apkstudio#191]
It shows no error if any setting is missing (e.g. path to adb.exe)
It simply does nothing.

It does not remember any path that I have entered (e.g. for APK file).
This is very sloppy programming.

It shows less information than JADX

It does not decompile smali files to Java.

I dont understand the usefulness of this project.
JADX is much better.

**Comment by vaibhavpandeyvpz** [comment]
Uninstall/remove & live your life.
