### ISSUE TITLE
Suggest GUI Toolkit to Build-upon

### ISSUE THREAD

**Issue by vaibhavpandeyvpz** [vaibhavpandeyvpz/apkstudio#2]
I am willing to revive this project & add new features but the QT confusing licensing policy is what had let me down. I read responses from people over XDA regarding not being able to run the Ubuntu version at all on their boxes because of missing libraries & QT does not seem to allow me to statically link itself in the binary.

So I am willing to discuss here on the GUI toolkit I should choose to deliever APK Studio in binary form usable straightaway to most developers. The toolkits + some additional platforms I can build it in are listed below, please make vote in comments to help me choose the most desired one.

1. As a Eclipse JDT Plug-in
2. As a Jetbrains IntelliJ Plug-in
3. QT (Do not want to, but will if I have to)
4. wxWidgets
5. SWT (Again from Eclipse)
6. JavaFX

**Comment by kirantpatil** [comment]
Hi,

Any guide on how to compile and install on Fedora ?

Even though you said it is not working on Ubuntu. 

Thanks.

**Comment by vaibhavpandeyvpz** [comment]
The version at Github is incomplete. You can get the source from Codeplex [link](http://apkstudio.codeplex.com/) and compile it over Fedora. Please note, Qt5 is a prequisite so better get to [Qt](http://www.qt.io/download/) website, download the community edition & then proceed with building.

**Comment by kirantpatil** [comment]
Sure, I will do it. But I could not find any steps to compile on Fedora or any Gnu/linux distribution. Please send me the steps to build.

**Comment by vaibhavpandeyvpz** [comment]
You should first give a try to the GUI way. Download & install Qt 5 community version, open Qt Creator, import the source from Codeplex and hit the Run button. It should compile fine.

**Comment by kirantpatil** [comment]
thanks will do it.

**Comment by kirantpatil** [comment]
one more toolkit to consider: http://www.gtk.org/

**Comment by kirantpatil** [comment]
http://shoesrb.com
https://github.com/shoes/shoes4

**Comment by JayXon** [comment]
IMO, Qt is the best choice if you want cross platform GUI, but if you don't want to, you could try wxWidgets.

**Comment by vaibhavpandeyvpz** [comment]
@JayXon I have re-written the thing with QT. Tried many others, but simply QT blew everything away when it came to features.
