### ISSUE TITLE
How to setup apk Studio?

### ISSUE THREAD

**Issue by dnyaneshwar129** [vaibhavpandeyvpz/apkstudio#20]
​Hello Vaibhav,
I have downloaded "vaibhavpandeyvpz-apkstudio-3.0.0-b6-2-gf9b4301.zip"

​
I have Windows-7 machine. 
when i unzip this folder, I am not able to understand how to install and setup Apk studio.

Could you please explains step by step process of setup and installation apk studio.

Before using APK Studio, you also need to install ADB.
What is ADB?

Thank you

**Comment by vaibhavpandeyvpz** [comment]
That is most probably the source archive. Please download an executable **(*exe)** [here](https://github.com/vaibhavpandeyvpz/apkstudio/releases) for Windows. ADB is a tool included in **Android SDK** already.

**Comment by dnyaneshwar129** [comment]
Thank You.

**Comment by MrRafat** [comment]
But i need your help another,, i face another problem....
