### ISSUE TITLE
vendor.zip offline

### ISSUE THREAD

**Issue by shlnz** [vaibhavpandeyvpz/apkstudio#22]
The [link](https://raw.githubusercontent.com/vaibhavpandeyvpz/apkstudio/master/external/vendor.zip)  is broken or "vendor.zip" is offline.

**Comment by edyshor** [comment]
Like i said in in the email i've sent you, [this link](https://bintray.com/artifact/download/vaibhavpandeyvpz/generic/2015.10.29/vendor.zip) in your [README.md](https://github.com/vaibhavpandeyvpz/apkstudio/blob/master/README.md) works.

**Comment by vaibhavpandeyvpz** [comment]
Believe @edyshor already answered your query.
