### ISSUE TITLE
[OSX] In-consistent control-sizing in Settings dialog

### ISSUE THREAD

**Issue by dogo** [vaibhavpandeyvpz/apkstudio#24]
Apkstudio runs fine on OSX, but I found a graphical glitch at "vendor path" as you can see :

![screen shot 2015-11-06 at 10 57 29 am](https://cloud.githubusercontent.com/assets/1487375/10997662/efdb143a-8475-11e5-8096-5665757bac53.png)

**Comment by vaibhavpandeyvpz** [comment]
This seems to be a layout sizing issue and unfortunately, I do not have a personal Mac to test & build on. Just wondering if you can try & send a pull request? The code for this class resides [here](https://github.com/vaibhavpandeyvpz/apkstudio/blob/master/src/preopenapk.cpp#L31) for your reference.

**Comment by MrRafat** [comment]
How to download this verasion...please give link or give 4share.com link....

**Comment by Surendrajat** [comment]
Clone this repo and follow Build instructions.
