### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by ViRb3** [vaibhavpandeyvpz/apkstudio#28]
I love APKStudio and even though it's super stable by itself, decoding and encoding the resources often doesn't work out well. 
* It would be really nice to have an option to only decompile the source and not touch resources at all. 
* Support for classes.dex files individually will also be very helpful.

Thanks!

**Comment by vaibhavpandeyvpz** [comment]
Added those source + resources options, see bf51710e34c21a8dff83dd59ff439c0e9f752157. Classes.dex only needs a bit of time. Will update binaries for Windows & Linux soon.

**Comment by vaibhavpandeyvpz** [comment]
Binaries updated. **classes.dex** thing is postponed for something in future as it requires wrapping around **baksmali** & things.
