### ISSUE TITLE
Vendor link download dead.

### ISSUE THREAD

**Issue by hariesnurikhwan** [vaibhavpandeyvpz/apkstudio#29]
Hi, 
it seems that the link for Vendor is dead.
https://bintray.com/artifact/download/vaibhavpandeyvpz/generic/2015.10.29/vendor.zip

Link from http://github.vaibhavpandey.com/apkstudio/ under "Instructions"

**Comment by tdec** [comment]
+1

**Comment by vaibhavpandeyvpz** [comment]
@hariesnurikhwan @tdec it's not a requirement now. updated website.

**Comment by hariesnurikhwan** [comment]
@vaibhavpandeyvpz I see, but I get an error when I want to decompile, it's related with apktool. Running on Mac OS X (El Capitan)

**Comment by vaibhavpandeyvpz** [comment]
oh, I see. You can download them from [here](http://bit.ly/db-public-apkstudio).
