### ISSUE TITLE
start apkstudio erro

### ISSUE THREAD

**Issue by kuake** [vaibhavpandeyvpz/apkstudio#30]
I get this, how to fix it? Thanks
![4fd0d8e6-77ff-4254-b046-90ed2181fbaa](https://cloud.githubusercontent.com/assets/815653/11295017/0a555266-8fa3-11e5-9b09-1ed0508d1d2f.png)

**Comment by hariesnurikhwan** [comment]
You can fix it by downloading this.
http://bit.ly/db-public-apkstudio

Extract the archive and place it here /Users/zl/.apkstudio

**Comment by vaibhavpandeyvpz** [comment]
:+1: @hariesnurikhwan
