### ISSUE TITLE
[OSX] Zipalign exited with code -1

### ISSUE THREAD

**Issue by hariesnurikhwan** [vaibhavpandeyvpz/apkstudio#31]
![image](https://cloud.githubusercontent.com/assets/10152692/11296868/b3f48ac4-8faf-11e5-89c9-4b88e2757b1b.png)

It seems there's some problem related with zipalign, jarsigner works fine.
but I was able to zipalign manually through terminal. So I guess there might be a bug or something.

**Comment by vaibhavpandeyvpz** [comment]
@hariesnurikhwan is **zipalign** in path or you run it from the SDK folder?

**Comment by hariesnurikhwan** [comment]
I didnt download the SDK, I get zipalign from here : http://stackoverflow.com/a/29999586 and place it here  "/usr/local/bin" so I could run the command via terminal. So I guess, yes zipalign is in path.

**Comment by vaibhavpandeyvpz** [comment]
I don't think /usr/local/bin is a standard path on **Max OSX**. You sure? APK Studio can only search either in **Standard Paths**, **ANDROID_SDK_HOME**. Alternatively you can place a copy of zipalign in **<user-home>/.apkstudio/vendor** and APK Studio should pick it up.

**Comment by hariesnurikhwan** [comment]
I'm not very sure about that but it's the same path where apktool ask to install (http://ibotpeaches.github.io/Apktool/install/). I have placed zipalign in <user-home>/.apkstudio/vendor and it's working. Thanks!
