### ISSUE TITLE
Error message about vendor.zip

### ISSUE THREAD

**Issue by wlritchi** [vaibhavpandeyvpz/apkstudio#32]
As I understand it, recent commits have made vendor.zip unnecessary. However, when apkstudio 9e114ca starts up, it still produces an error message asking the user to download and install third party libraries from the website, even though the website doesn't have a link for them. Ignoring this and attempting to decompile an apk fails with

    Error: Unable to access jarfile apktool.jar
Are the installation instructions incomplete?

**Comment by vaibhavpandeyvpz** [comment]
I am now distributing precompiled binaries for linux i386 & x86_64 platforms. Building from source is now going to require users to place [apktool.jar](https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.0.2.jar) file & a blank file with name **VERSION** in ~/.apkstudio/vendor atm. I am busy implementing some sort of online downloading & updating of those binaries by apkstudio itself which should remove this trouble.

I apologize for troubling you everytime regarding this **vendor.zip** thing but I really kind of indecisive on how to handle it's *install* & *update*. That's the reason I made a switch to native installers to ease things for new users.

**Comment by stephdgenius** [comment]
how to change window title of apkstudio ?

**Comment by vaibhavpandeyvpz** [comment]
There they are: https://github.com/vaibhavpandeyvpz/apkstudio/blob/master/res/lang/en.ts#L448

**Comment by stephdgenius** [comment]
thanks !

**Comment by stephdgenius** [comment]
i have not en.qm resource file in my project. How to create en.qm ?

**Comment by vaibhavpandeyvpz** [comment]
in project directory, run ```lrelease res/lang/en.ts``` or you can use **Qt Linguist** to compile ```res/lang/en.ts``` to ```res/lang/en.qm```.

**Comment by stephdgenius** [comment]
Thank you again !
And how to resolve the message that appears about vendor ?

**Comment by vaibhavpandeyvpz** [comment]
you just need to put ```apktool.jar``` anda blank file with name ```VERSION``` in **~/.apkstudio/vendor**

**Comment by wlritchi** [comment]
I'm closing this as I've managed to work around it for packaging on Arch by using a setup script to place the necessary files. I still think having the option of installing apktool systemwide would be preferable (either by defining a path where the system copy can be found, or by detecting `apktool` on the path), but that's a separate issue.
