### ISSUE TITLE
Bro WTF just did happen to my desktop?????????????????

### ISSUE THREAD

**Issue by biggdawgg09** [vaibhavpandeyvpz/apkstudio#33]
Lol man are you seriously doing something COMPLETELLY different from actual idea?I just chosed some apk to decompile,the source project home to be put afterwards i chossed my desktop,hit ok and the freaking programm started to delete everything on my destkop...man i will ask,WTF?thank you man i got very freakin important files COMPLETELLY  deleted....what the hell man...

**Comment by vaibhavpandeyvpz** [comment]
all I can say ... oops! :grin: you should look left-right twice before crossing roads.

**Comment by biggdawgg09** [comment]
Man ur kidding me???lmfao :D oops yeahd and i got fucked up lol

**Comment by vaibhavpandeyvpz** [comment]
well you know very well I can't help you with that. apologies!

**Comment by rocxteady** [comment]
My Downloads folder was deleted completely either!
