### ISSUE TITLE
Ubuntu 15.10 x64 apkstudio/d49d3de/./apkstudio: error while loading shared libraries: libicui18n.so.52: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jawz101** [vaibhavpandeyvpz/apkstudio#35]
afaik Ubuntu Wily 15.10 has libicu55 not 52 if that means something

@ubuntu-mate:~/apkstudio/d49d3de$ sh apkstudio.sh 
/home/.../apkstudio/d49d3de/./apkstudio: error while loading shared libraries: libicui18n.so.52: cannot open shared object file: No such file or directory

**Comment by jawz101** [comment]
nm.  I don't think you're supposed to run the program via the shell script.  I'll leave it open if this error is relevant for anything but the dev can close it.

**Comment by vaibhavpandeyvpz** [comment]
libicui18n = ```lib``` + ```icu``` + ```i18n```

To install this missing lib:
- Download the **debian package *.deb** from [here](http://packages.ubuntu.com/trusty/amd64/libicu52/download).
- Install it from command line using ```sudo dpkg -i libicu52_52.1-3ubuntu0.4_amd64.deb```
