### ISSUE TITLE
KIO Connection server not listening, could not connect

### ISSUE THREAD

**Issue by sherpya** [vaibhavpandeyvpz/apkstudio#37]
I'm using kde5, I get this error when apkstudio launches open file dialog, the file dialog becomes almost unusable (it does not select), a workaround is to create /run/user/$(id -u)/apkstudio directory by hand

**Comment by vaibhavpandeyvpz** [comment]
Another way is you can build it from source with ```-DNO_NATIVE_DIALOG``` flag, then **APK Studio** will not use native dialogs, and use custom Qt thing which doesn't mess up.

**Comment by sherpya** [comment]
wontfix? it's a kde problem?

**Comment by vaibhavpandeyvpz** [comment]
Most probably. I tested it myself throughly as I initially developed this version on KDE Plasma (you can check it in the [Wiki](https://github.com/vaibhavpandeyvpz/apkstudio/wiki/Building)). I also have provided a workaround for this issue as documented in build instructions [here](https://github.com/vaibhavpandeyvpz/apkstudio/blob/master/README.md) but it requires building from source.
