### ISSUE TITLE
Problem opening APK

### ISSUE THREAD

**Issue by umoran** [vaibhavpandeyvpz/apkstudio#39]
The following message displayed:

$ java -Xmx128m -jar C:/Users/urim/.apkstudio/vendor/apktool.jar -f d C:/Users/urim/Desktop/com.screentime.rc.apk -o C:/Users/urim/Desktop/com.screentime.rc
Process exited with code -1

**Comment by vaibhavpandeyvpz** [comment]
Do you have java in **PATH** or have **JAVA_HOME** set?
