### ISSUE TITLE
Error in apkstudio

### ISSUE THREAD

**Issue by kirantpatil** [vaibhavpandeyvpz/apkstudio#4]
$ java -Xms512m -jar /home/kpatil/apkstudio/bin/apktool.jar --force --frame-path /home/kpatil/apktool/framework --frame-tag 7Toel1s3 --verbose if "/home/kpatil/Documents/nRF MasterControlPanel.apk"

**Comment by kirantpatil** [comment]
I also see that in fedora I see UI little different 

![screenshot from 2015-05-16 14-52-33](https://cloud.githubusercontent.com/assets/1178055/7665564/3751aa96-fbdb-11e4-97f6-f1cbc6a020d1.png)

**Comment by vaibhavpandeyvpz** [comment]
I see you are compiling the code from Github. Please try compiling code from 2.0.x hosted on [Codeplex](http://apkstudio.codeplex.com).

**Comment by kirantpatil** [comment]
yes, now got it.
