### ISSUE TITLE
failed to decode

### ISSUE THREAD

**Issue by Jonsonyami** [vaibhavpandeyvpz/apkstudio#40]
hello...
plz check below screenshot.and try to solve it.
![screenshot_2](https://cloud.githubusercontent.com/assets/12223893/12543854/de4bea3c-c359-11e5-9fc6-21168e853c83.png)

**Comment by vaibhavpandeyvpz** [comment]
you java --version?

**Comment by nopran** [comment]
1.8.0

**Comment by Jonsonyami** [comment]
yes

**Comment by Jonsonyami** [comment]
asking for apk studio version?

**Comment by Jonsonyami** [comment]
1.6.0

**Comment by vaibhavpandeyvpz** [comment]
If this APK if from Kitkat or newer, you may need to install JDK 7
