### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by nopran** [vaibhavpandeyvpz/apkstudio#41]
![problem](https://cloud.githubusercontent.com/assets/16913686/12607559/7d5a896c-c508-11e5-9ac5-8364f8261065.PNG)

**Comment by vaibhavpandeyvpz** [comment]
most probably it's a lack of framework resources.

**Comment by ProGrammeGUY** [comment]
@nopran You can try this Framework-res. Download [Here](https://www.androidfilehost.com/?fid=23212708291677144)

**Comment by nopran** [comment]
@ProGrammeGUY  how to settings Framework-res ?

**Comment by nopran** [comment]
@ProGrammeGUY how to settings Framework-res ?
