### ISSUE TITLE
Can't install .apk after build

### ISSUE THREAD

**Issue by emanf** [vaibhavpandeyvpz/apkstudio#42]
hi,

i opened a apk file and i didnt change anything i just click on **build** and then **install** but i got below error even after some basic change.

```
$ java -Xmx128m -jar apktool.jar -f b "some" -o "someother"
I: Using Apktool 2.0.2
I: Smaling smali folder into classes.dex...
I: Building resources...
warning: string 'Clic_return_to_parent' has no default translation.
I: Copying libs... (/lib)
I: Building apk file...
Process exited with code 0
```

```
$ adb install -r "somename.apk"
    pkg: /data/local/tmp/somename.apk
Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION]
rm failed for -f, No such file or directory
6221 KB/s (19589929 bytes in 3.075s)
Process exited with code 0
```

can you help me about it?

**Comment by emanf** [comment]
ok now it works. i just forgot to resign the apk.

**Comment by JackLauu** [comment]
Could you tell me how to resign the apk? I download a apk from google play, use apkstudio decode it, and change the debuggable option, then build it, but can't install. Is it because I don't use the apk's sign? How to do it?

**Comment by GitHubian** [comment]
Well @JackLauu If you are not quite familiar to Apkstudio you can use [Apktool](https://ibotpeaches.github.io/Apktool/) in which you can use the Apk decompile,Recompile and then sign it use[ this](https://www.cheaterzclub.com/decompile-recompile-apk-file-using-apktool/) link to know how to sign apk using Apktool ☑

**Comment by clfdhq** [comment]
Process exited with code -1
what up?, can you help me

**Comment by Surendrajat** [comment]
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
