### ISSUE TITLE
Failed to decode

### ISSUE THREAD

**Issue by ghost** [vaibhavpandeyvpz/apkstudio#43]
When i was trying to decode apps it says failed to decode [...] Please check output.
The console says : app exited with code -1

**Comment by ProGrammeGUY** [comment]
@AtiPLS Actually You need to create a path 
For Example: You want to decompile whatsapp.apk , first go to desktop create a folder named "Projects" then create a subfolder named "com.filename.whatever"(format must be same doesnt matter what you name ) and in that sub folder you decompile/decode you app! 💻
