### ISSUE TITLE
Cannot find the .apk file in the build folder

### ISSUE THREAD

**Issue by VivekGadhvi** [vaibhavpandeyvpz/apkstudio#44]
After Compiling the Apk , When I saw the Build Folder There was nothing in it Only a sub-folder named 'apk' whats the reason behind it?
Please reply me Soon.

**Comment by behru7** [comment]
also my problem!!
the apk file does not appear in the build folder anymore but in will be replaced with the current apk file you are decoding.
But it does not work on device when you try to install it. A parsing error is displayed on my mobile screen. Do you know how to solve it?
are the previous versions of apk studio available?

**Comment by ProGrammeGUY** [comment]
Well these might be the problems for the parse error.
1) You might have messed up androidmanifest.xml
2) You must zip align the app
3) You must sign the app ( Thats Important One )
