### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by alonjin** [vaibhavpandeyvpz/apkstudio#45]
please check output
What did I do wrong?

**Comment by vaibhavpandeyvpz** [comment]
where is the output?

**Comment by alonjin** [comment]
what do you mean? project path?

הודעת דוא"ל זו נשלחה ממחשב נקי מווירוסים המוגן על ידי Avast.‏
www.avast.com <https://www.avast.com/sig-email>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-02-16 10:51 GMT+02:00 Vaibhav Pandey <notifications@github.com>:

**Comment by vaibhavpandeyvpz** [comment]
the console output
