### ISSUE TITLE
Sign APK doesn't work.

### ISSUE THREAD

**Issue by y0ursource** [vaibhavpandeyvpz/apkstudio#46]
Hello, I really love the app much better in size than the official Android Studio app.
I cannot get the sign apk to work, i've tried everything. 

It would be great totally amazing if you could make a create keystore feature in this app.

It's completely pointless leaving this feature out, I mean why have such a great GUI for editing APKs/building them, and all the contents of the zip, but then expect people to go back to command line keytool when it comes to trying to sign the damn apk lol (Kind of completely misses the point of a GUI tool for editing apks if you have to then resort back to cmd to use keytool to get the keystore file. 
Why isn't this a core feature? To be-able to create a quick keystore instead of expecting the user to already have one?

I've created my keystore with Android Studio, With APK Editor, With ZipSigner all work fine.
But when trying to fill in your APK sign wizard box using the EXACT same keystore file as with all other apk editors when I go to install the apk on my device it says all the time error parasing info. 

I can then take the same apk do it with ZipSigner, APK Editor or even Android Studio and it installs fine. Something is so wrong with this signing process as the same keystore file works on other authors programs.

**Comment by Surendrajat** [comment]
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
