### ISSUE TITLE
linux install issues

### ISSUE THREAD

**Issue by dimonik** [vaibhavpandeyvpz/apkstudio#48]
Hi!

I used this binary https://bintray.com/artifact/download/vaibhavpandeyvpz/generic/apkstudio/d49d3de/apkstudio-d49d3de-linux-x64.run

on my Ubuntu x64.

Installer successfully completed it's job.

But when i went to
.../apkstudio/d49d3de/
and run ./apkstudio
i got
./apkstudio: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory

i tried to run
./apkstudio.sh
i got
This application failed to start because it could not find or load the Qt platform plugin "xcb".
Available platform plugins are: xcb.
Reinstalling the application may fix this problem.
Aborted (core dumped)

But all the libs are present in the /d49d3de/ directory.

How to solve this?

**Comment by mzozo95** [comment]
Any update? I have the same issue. The required _so_ file is next to the apktool file, but it seems apktool can not access it.

**Comment by mzozo95** [comment]
**Solution**: build it to yourself!
Before build install qt5 dev like this:

`sudo apt-get install qttools5-dev-tools`

Build instcutrion is in the _md_ file.

**Comment by Surendrajat** [comment]
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
