### ISSUE TITLE
Create button is not enabling to decompile apk file

### ISSUE THREAD

**Issue by kirantpatil** [vaibhavpandeyvpz/apkstudio#5]
![screenshot from 2015-05-16 15-34-07](https://cloud.githubusercontent.com/assets/1178055/7665674/0fd41a66-fbe1-11e4-909e-b503fb9d74cd.png)

**Comment by vaibhavpandeyvpz** [comment]
Make sure the project name does not have any thing else [a-zA-Z0-9], not even spaces ;-) I will improve this.

**Comment by kirantpatil** [comment]
Is it because it could not find apktool ?

I have installed it as shown below and did command line decompile as well.

[kpatil@dhcppc21 source]$ whereis apktool
apktool: /usr/local/bin/apktool

How should I fix this issue ?

**Comment by kirantpatil** [comment]
ok fine.

**Comment by kirantpatil** [comment]
Yes it works now.
