### ISSUE TITLE
Stop Working

### ISSUE THREAD

**Issue by almaddy95** [vaibhavpandeyvpz/apkstudio#50]
I've an issue that when I de-compile an apk file, it start to ruin my work. After spending more than a half hour, the application stop to processing and it force to close without asking to save them. My pc spec is in good condition. I dnt know if the application or my pc had the problem. Please solve this issue. Thanks for great distribution on this software. Great! Keep it up !

**Comment by Surendrajat** [comment]
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
