### ISSUE TITLE
Cannot Decompile APK

### ISSUE THREAD

**Issue by Kneesnap** [vaibhavpandeyvpz/apkstudio#52]
When decompiling a certain APK file, I get this error.
![image](https://cloud.githubusercontent.com/assets/6562913/14591134/32c23074-04c0-11e6-9735-84ffdd649c9a.png)
I can provide the apk if needed

**Comment by Xstar97** [comment]
reinstall apk studio  make sure to have all the requried dependencies & compaitble java installed....However it seems the apk could be obfuscated(misspelled) & thats why it cant decompile
