### ISSUE TITLE
I am not able to complete the installation.

### ISSUE THREAD

**Issue by iamnewspecies** [vaibhavpandeyvpz/apkstudio#53]
When I open it I get the following message. How should i fix it?
![screenshot from 2016-05-02 14-35-55](https://cloud.githubusercontent.com/assets/1262584/14951005/b05c880e-1073-11e6-9407-a7307398e344.png)

If you click on "here" link it opens this http://www.vaibhavpandey.com/apkstudio/ 
Which has nothing that helps.

**Comment by Xstar97** [comment]
Please download the apktool jar & excutable script from here....
http://connortumbleson.com/2016/05/07/apktool-v2-1-1-released/

download both files & renamed them apktool.jar & apktool.sh respectively & placed them in the vendor folder

**Comment by Surendrajat** [comment]
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
