### ISSUE TITLE
NO SRC after decompiling

### ISSUE THREAD

**Issue by atul1112** [vaibhavpandeyvpz/apkstudio#55]
Hi @vaibhavpandeyvpz ,

First of all thank you for this tool.
But im having one issue after decompiling an apk.

After decompiling an apk im not able to see any SRC folder with all the java code inside.
All i can see is res, smali and other folder.

I want to edit one line java code but stuck here.

i also tried to decompile it from http://www.decompileandroid.com/,  and copied the src folder from here to apkstudio project. 
But after building apk, it overwrite my code in src file.

Real Help Needed in this.

Thanks,
ATUL

**Comment by atul1112** [comment]
I think i got it,

I can see the constants declared in smali that i can change.
Issue solved.

Thanks

**Comment by Xstar97** [comment]
when you decompile an apk...you get smali NOT java....also you really cant(shouldn't) edit that type of source anyway.
