### ISSUE TITLE
Error application not installed

### ISSUE THREAD

**Issue by w3stking** [vaibhavpandeyvpz/apkstudio#58]
i decompile recompile with no changes (more than 10 apps from google play store) 

and when i tried to install the apps on my android devices cellphone and tablet it says 

X application not installed

how to fix it??

**Comment by goofyman777** [comment]
there should be 1 app thats able to do all of this. I hate having to use 10 or 20 different apps compiler, decompiler(s), xml deporter xml importer, java console, jre builder, html builder, etc. if they cant do it right then they sould not do it at all is my motto and opinion(s). technically it should read How do I fix this? or How do I fix this problem but lol to each their own. id start off simple btw I would try backing up the file(s) or apk(s) just in case it doesnt work and then manually change program type to .APK all capital letters as android devices wont auto install anything with lowercase extensions. once this is done if the file is on your pc connect you device cable to the pc and to your device and send the file via either drag and drop method or via the transfer files method of copy or move file to commands once on your device select file you just place on the android device and try to instal it using package instaler another option is by sd card place the file or files on the sd card and insert the card into your device. this is just how i would do it if it were me. but again I cant get apk studio to even install to decompile so lol might not be the best one for advice.

**Comment by Surendrajat** [comment]
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).

**Comment by JanisSharma** [comment]
Already solved At [here](icetutor.com/question/app-not-installed-error-on-android)
