### ISSUE TITLE
No installer and will not work with windows xp 

### ISSUE THREAD

**Issue by goofyman777** [vaibhavpandeyvpz/apkstudio#59]
this zip file that's available for download is junk ! there's no exe file no installer and no XML files that allow mounting of files via the instalbuilder app thing. If you are going to make an apk studio at least take the time and do it right and include an installer and detailed instructions how to install the program(s). another thing is the choppy overseas, hacker typing language( shorthand choppy English or short incomplete sentences) for example point to adb folder next then make sure jre etc. you see what i mean? totally uncomprehendable to most. Now please slow down and tell us how to install this and make it work with windows xp, windows 7 and windows 8 in full sentences and don't point us to some piece of junk website.

**Comment by Tr4sHCr4fT** [comment]
the installer is linked on their homepage

**Comment by Surendrajat** [comment]
Now portable binaries are available and the third party tools are needed to be downloaded separately.
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
