### ISSUE TITLE
Failed decompile apk file

### ISSUE THREAD

**Issue by kirantpatil** [vaibhavpandeyvpz/apkstudio#6]
I tried to create new project and provided the apk file to decompile but it is not happening as shown below screenshot

![screenshot from 2015-05-16 15-39-25](https://cloud.githubusercontent.com/assets/1178055/7665696/c919f0a4-fbe1-11e4-8b4f-c2ffbf6a332a.png)

**Comment by vaibhavpandeyvpz** [comment]
Did you setup everything (apktools, aapt & all) is Settings?

**Comment by kirantpatil** [comment]
The settings does not contain about apktools and all.

Please find the below screenshot.
![screenshot from 2015-05-16 15-45-40](https://cloud.githubusercontent.com/assets/1178055/7665720/b049d0b6-fbe2-11e4-8bad-af41f1faad2e.png)

**Comment by vaibhavpandeyvpz** [comment]
The "Binaries" path should contain all required files. Wait a few minutes, I will zip things up and send you link here.

**Comment by kirantpatil** [comment]
Ok, Thanks.

**Comment by vaibhavpandeyvpz** [comment]
You can simply download [this](http://apkstudio.codeplex.com/downloads/get/909467) file & get the binaries folder from therein.

**Comment by kirantpatil** [comment]
There is no binaries folder in the path as shown below.

[kpatil@dhcppc21 apkstudio]$ ls /home/kpatil/Documents/build-apkstudio-Desktop_Qt_5_4_1_GCC_64bit-Debug/
about.o               moc_editors.cpp      moc_rename.cpp
adb.o                 moc_editors.o        moc_rename.o
add.o                 moc_file.cpp         moc_rm.cpp
apkstudio             moc_file.o           moc_rm.o
applications.o        moc_files.cpp        moc_screenshot.cpp
browser.o             moc_files.o          moc_screenshot.o
build.o               moc_find.cpp         moc_settings.cpp
chmod.o               moc_find.o           moc_settings.o
coder.o               moc_framework.cpp    moc_state.cpp
completer.o           moc_framework.o      moc_state.o
decompile.o           moc_highlighter.cpp  moc_statusbar.cpp
devices.o             moc_highlighter.o    moc_statusbar.o
editors.o             moc_ide.cpp          moc_toolbar.cpp
file.o                moc_ide.o            moc_toolbar.o
files.o               moc_imei.cpp         moc_uninstall.cpp
find.o                moc_imei.o           moc_uninstall.o
format.o              moc_information.cpp  new.o
framework.o           moc_information.o    package.o
highlighter.o         moc_install.cpp      partition.o
ide.o                 moc_install.o        partitions.o
imei.o                moc_logcat.cpp       permissions.o
information.o         moc_logcat.o         project.o
install.o             moc_logger.cpp       projects.o
logcat.o              moc_logger.o         pull.o
logger.o              moc_menubar.cpp      push.o
main.o                moc_menubar.o        qrc_completion.cpp
Makefile              moc_new.cpp          qrc_completion.o
menubar.o             moc_new.o            qrc_font.cpp
moc_about.cpp         moc_package.cpp      qrc_font.o
moc_about.o           moc_package.o        qrc_highlight.cpp
moc_adb.cpp           moc_partition.cpp    qrc_highlight.o
moc_adb.o             moc_partition.o      qrc_icon.cpp
moc_add.cpp           moc_partitions.cpp   qrc_icon.o
moc_add.o             moc_partitions.o     qrc_language.cpp
moc_applications.cpp  moc_permissions.cpp  qrc_language.o
moc_applications.o    moc_permissions.o    recompile.o
moc_browser.cpp       moc_project.cpp      refresh.o
moc_browser.o         moc_project.o        remount.o
moc_build.cpp         moc_projects.cpp     rename.o
moc_build.o           moc_projects.o       rm.o
moc_chmod.cpp         moc_pull.cpp         screenshot.o
moc_chmod.o           moc_pull.o           settings.o
moc_coder.cpp         moc_push.cpp         state.o
moc_coder.o           moc_push.o           statusbar.o
moc_completer.cpp     moc_recompile.cpp    text.o
moc_completer.o       moc_recompile.o      toolbar.o
moc_decompile.cpp     moc_refresh.cpp      ui.o
moc_decompile.o       moc_refresh.o        uninstall.o
moc_devices.cpp       moc_remount.cpp      xmlhighlighter.o
moc_devices.o         moc_remount.o
[kpatil@dhcppc21 apkstudio]$

**Comment by kirantpatil** [comment]
I copied the binaries directory to specified path and getting below error

I: Using Apktool 2.0.0-Beta9 on nRF MasterControlPanel.apk
I: Loading resource table...
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/kpatil/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x0000001d
I: Loading resource table from file: /home/kpatil/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x00000018
I: Loading resource table from file: /home/kpatil/apktool/framework/1.apk
Cleaning up unclosed ZipFile for archive /home/kpatil/apktool/framework/1.apk
Cleaning up unclosed ZipFile for archive /home/kpatil/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x0000001d
I: Loading resource table from file: /home/kpatil/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x00000018
Exception in thread "main" java.lang.NullPointerException
	at java.io.Writer.write(Writer.java:157)
	at brut.androlib.res.util.ExtMXSerializer.writeAttributeValue(ExtMXSerializer.java:38)
	at org.xmlpull.mxp1_serializer.MXSerializer.attribute(MXSerializer.java:673)
	at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.attribute(XmlSerializerDelegate.java:106)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:87)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:146)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:160)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:131)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:276)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:116)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:114)
	at brut.apktool.Main.cmdDecode(Main.java:169)
	at brut.apktool.Main.main(Main.java:85)

**Comment by vaibhavpandeyvpz** [comment]
For which platform this APK was compiled? Have you tried adding your framework and using it while decompiling?

**Comment by kirantpatil** [comment]
I am on Fedora 22.

Which framework should I add and how to add it ?

**Comment by kirantpatil** [comment]
I am downloading framework from https://www.androidfilehost.com/?fid=23212708291677144 and will try on it and let you know.

**Comment by kirantpatil** [comment]
The framework expects tag to install, from where should I get the tag.

**Comment by kirantpatil** [comment]
Now I installed it but still it is giving the same error.

I: Using Apktool 2.0.0-Beta9 on nRF MasterControlPanel.apk
I: Loading resource table...
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/kpatil/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x0000001d
I: Loading resource table from file: /home/kpatil/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x00000018
I: Loading resource table from file: /home/kpatil/apktool/framework/1.apk
Cleaning up unclosed ZipFile for archive /home/kpatil/apktool/framework/1.apk
Cleaning up unclosed ZipFile for archive /home/kpatil/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x0000001d
I: Loading resource table from file: /home/kpatil/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x00000018
Exception in thread "main" java.lang.NullPointerException
	at java.io.Writer.write(Writer.java:157)
	at brut.androlib.res.util.ExtMXSerializer.writeAttributeValue(ExtMXSerializer.java:38)
	at org.xmlpull.mxp1_serializer.MXSerializer.attribute(MXSerializer.java:673)
	at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.attribute(XmlSerializerDelegate.java:106)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:87)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:146)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:160)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:131)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:276)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:116)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:114)
	at brut.apktool.Main.cmdDecode(Main.java:169)
	at brut.apktool.Main.main(Main.java:85)

**Comment by kirantpatil** [comment]
is that because of java version ?

I am on java-1.8

**Comment by vaibhavpandeyvpz** [comment]
Can you provide me with APK you are decompiling if possible? Will help me dig down to exact issue. Though it is related to apktool, as decompiling is done by apktool only.

**Comment by kirantpatil** [comment]
I am also suspecting that the issue may be related to apktool.

Anyway you can download the apk file from this link,
https://www.nordicsemi.com/eng/nordic/Products/nRF-Master-Control-Panel-application/nRF-Master-Control-Panel-APK-for-Android-4.3/36818

**Comment by call5** [comment]
hello, I have also the same issue but I'm on Windows 8, I tried with the application in 2048 (https://fossdroid.com/a/2048.html) but I always have this error. thank you for feedback I did not want to open another ticket as it is essentially the same problem

![Image of screenshot1](https://i.imgur.com/o1j4MlM.png)

![Image of screenshot2](https://i.imgur.com/1toG7Ee.png)

**Comment by heinermann** [comment]
I think this issue revolves around the "Frameworks" box being undocumented. Even seasoned developers/hackers aren't going to know what this is for. There is zero documentation on getting started or what this is even used for. "Frameworks" could mean anything.

**Comment by vaibhavpandeyvpz** [comment]
The framework thing used to be used to play with System apps. They reference resources from framework-res.apk and similar files on /system partition in the phone. apktool needs those files to be installed earlier into its cache before attempting to decompile/recompile a System app.

For the while, I have removed the frameworks things as I rewriting the app from scratch.

**Comment by vaibhavpandeyvpz** [comment]
@kirantpatil the **apktool** included with the previous builds was old & beta. I have updated APK Studio with new + stable apktool *2.0.1* (at the time of this comment) and was successful in decompiling the provided APK. You can check [Releases](https://github.com/vaibhavpandeyvpz/apkstudio/releases) to download the package for Windows or build from source for Linux.

**Comment by jhunee** [comment]
Please how fix this... i tried to decompile app from ASUS ZENFONE 5 (x86) 

$ java -Xmx128m -jar C:/Users/herma/.apkstudio/vendor/apktool.jar -f d "D:/JHUN/PROJECT THEMED/ASUS/SETTING/AsusSettings.apk" -o "D:/JHUN/PROJECT THEMED/ASUS/SETTING/AsusSettings"
I: Using Apktool 2.1.1 on AsusSettings.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\herma\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=summary, value=0x01040682
W: Could not decode attr value, using undecoded value instead: ns=android, name=textColor, value=0x01060191
S: Could not decode file, replacing by FALSE value: drawable-xhdpi-v4/asus_btn_status_indicator_on_dark.png
W: Could not decode attr value, using undecoded value instead: ns=android, name=textColor, value=0x01060191
W: Could not decode attr value, using undecoded value instead: ns=android, name=textColor, value=0x01060191
W: Could not decode attr value, using undecoded value instead: ns=android, name=textColor, value=0x01060191
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x010304e4
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:66)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:62)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
	at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResReferenceValue.java:47)
	at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlAttr(ResScalarValue.java:46)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:49)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:513)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:264)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:128)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:81)
