### ISSUE TITLE
Zipalign not working at all for apk signing

### ISSUE THREAD

**Issue by bluedog4** [vaibhavpandeyvpz/apkstudio#62]
In the latest version, every time I sign an app, it works fine until the end when zipalign is used to copy the apk, it always fails with an exit code of -1. Other than that, app works great!

**Comment by koko-ng** [comment]
I resolved it,
Just locate your android sdk path then symlink/copy buildtools/_ANDROID-VERSION_/zipalign to .apkstudio/vendor (where you put apktool). Then just restart apkstudio.

**Comment by Surendrajat** [comment]
You don't need `zipalign` now unless you're using linux 32bit.
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
