### ISSUE TITLE
APKStudio: recompile issue on styles.xml

### ISSUE THREAD

**Issue by emsculptor** [vaibhavpandeyvpz/apkstudio#63]
I just installed and decompiled successfully. 
But upon the Build I get an error referring to the styles.xml: 
res\values-v39\styles.xml:7: error: Error retrieving parent for item: No resource
Do I need to suppress some files or execut a CMD command.

Looking forward to a reply.

**Comment by VivekGadhvi** [comment]
Greetings! The problem is that you have not implemeted the parent item's code above the child code! To resolve this error just write down the parent item code above the code depicting error! This is a sort of common problem in apk studio.Cheers!
