### ISSUE TITLE
Set JAVA path

### ISSUE THREAD

**Issue by Habibah28** [vaibhavpandeyvpz/apkstudio#64]
Java: n/a
ADB: n/a
APK tool: n/a

How to set JDK path? Didn't found in setting or anything.

**Comment by lbray** [comment]
To set the JAVA_HOME path on Linux you would...

Edit environment file...
    `sudo nano /etc/environment`
At the bottom of that file put a line with the full path for your Java and a line to export the variable. So for my system i added this to the bottom of the file...
```
    JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    export JAVA_HOME

```
Save the file and exit the editor.
Reload the environment by typing this at the terminal...
`    . /etc/environment
`
Please note that there is a [space] character right after the "." and right before the "/etc"
