### ISSUE TITLE
Decodeing file-resources fail

### ISSUE THREAD

**Issue by adthk** [vaibhavpandeyvpz/apkstudio#65]
Trying to Decode apk file - [https://dailyuploads.net/cmbb7h9kqbey](url) 
with Apk Studio d49d3de on Windows 7 ultimate x64 , java 8 x64 System. but there is an error while decodeing resources and source.
Please help...
![Apk Studio Error Screenshot](https://cloud.githubusercontent.com/assets/7888999/19073296/d562bd18-8a57-11e6-9e96-d45a7d15d7fb.JPG)

**Comment by VivekGadhvi** [comment]
Hello! @adthk I think you have an old version of 𝐟𝐫𝐚𝐦𝐞𝐰𝐨𝐫𝐤.𝐚𝐩𝐤 ,I recommend you to replace it with [this](https://basketbuild.com/filedl/devs?dev=aniruddhc&dl=aniruddhc/framework-res.apk) .
Hope this helped you out!

**Comment by Surendrajat** [comment]
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
