### ISSUE TITLE
Build process instruction breakdowns

### ISSUE THREAD

**Issue by huttarl** [vaibhavpandeyvpz/apkstudio#66]
I'm following the instructions [here](https://github.com/vaibhavpandeyvpz/apkstudio/wiki/Building). I'm using Mac OSX El Capitan, FWIW.

On step 2 it says, `You may want to build a release, instead of development master`, and
`git checkout tags/3.0.0-b5`
But that command results in the following error:
`error: pathspec 'tags/3.0.0-b5' did not match any file(s) known to git.`
And no wonder ... there don't seem to be any tags in the repo. At least, not that I can find.
I tried `git checkout tags/3.0.0` but got the same error.

So that's the first problem with the build process. There doesn't seem to be any clear way to build a release, despite the comment about doing so.

However, I leave it at HEAD and proceed with the remaining steps. After successfully building the project in step 9, step 10 says to click on the Run button to launch. But Qt Creator is unable to find the executable. Browsing through the directory tree where the repo was cloned doesn't yield any clues. This is the second problem.

I eventually discovered, by reading the Compile Output, that the executable was being built at `../build-apkstudio-Desktop_Qt_5_5_1_clang_64bit-Release/apkstudio.app` relative to `apkstudio` where I cloned the source code.

Third, once APK Studio is launched, when you try to open an APK, APK Studio shows a dialog with the following message: 
`You need to download some 3rd-party applications/files from [here](http://www.vaibhavpandey.com/apkstudio/) and place them in (my home directory)/.apkstudio/vendor for APK Studio to work.`

But when I follow that link, I find nothing about 3rd-party applications/files to put in the vendor folder. The only downloads mentioned there are native installers for APK Studio for various platforms, but I have already installed APK Studio (and anyway, Mac OSX is not included there). 

Frustratingly, the message gives no indication of what sort of applications/files need to be downloaded and installed. I already have JAVA_HOME pointing to a JDK, and I have adb in my path, as the instructions on the linked page specify.

When I try to open an APK in APK Studio, I get an error 
`Unable to access jarfile apktool.jar` in the Console. Maybe apktool.jar is what I need to download and put in the `vendor` directory?
I went through that process, and the result was as follows:
- the "You need to download some 3rd-party applications/files" message remains, indicating that the problem is not yet (fully) solved.
- the error about being unable to find apktool.jar goes away, and APK Studio seems to have some success in showing the contents of the APK.

That was a frustrating amount of trial-and-error/guesswork, and I have no idea what other tools I'm missing that will prevent features from working.

I'd be happy to submit a PR with an addendum to the instructions for the 2nd problem and part of the 3rd (what other files am I missing?). But I don't know what the solution is for the first issue. Should the instruction to checkout a tag just be deleted? or do the tags exist somewhere, and I'm just not finding them?

**Comment by IvoPereira** [comment]
+1 here. I am having the same exact problems in all the steps you mentioned.

**Comment by DaPa** [comment]
"apktool.jar" and "apktool.bat" seems to be enough in "\.apkstudio\vendor\".
To stop "You need to download some 3rd-party..." message, in the same "\.apkstudio\vendor\" create also a "VERSION" folder.

**Comment by baksosapi** [comment]
Download apktool and save to /Users/[username]/.apkstudio/vendor
```
wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.3.0.jar
```
rename it to ``` apktool.jar ```
Restart apps.
It works well for me.

**Comment by Surendrajat** [comment]
[Wiki](https://github.com/vaibhavpandeyvpz/apkstudio/wiki) is updated with latest info about building.
To solve other Run-Time issues download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).

**Comment by ScubaInstructor** [comment]
I built apkstudio with qt 5.12. The UI looks not really slick.
I am wondering where adb & zipalign need to be installed (path) for apkstudio to find it? Any suggestions?
