### ISSUE TITLE
Feature request: Add keystore management capabilities

### ISSUE THREAD

**Issue by raulsiles** [vaibhavpandeyvpz/apkstudio#67]
I think it would be very interesting to add keystore management capabilities to APK Studio, so that it can invoke keytool with the right parameters to (at least) create the Android developer keystore required to sign the APK if it does not exist on a given location (managed through preferences) when required by jarsigner, or the first time the tool is used (via a wizard). 

This way the whole reverse engineering process would be self-contained within the tool.

**Comment by Surendrajat** [comment]
Creation of KeyStore isn't mandatory anymore, it's optional. Thanks to [`uber-apk-signer`](https://github.com/patrickfav/uber-apk-signer). APK's will be signed with an embedded keystore for better automation.
