### ISSUE TITLE
Feature request: Add an option to include the Network Security Configuration file

### ISSUE THREAD

**Issue by raulsiles** [vaibhavpandeyvpz/apkstudio#68]
It would be very useful to have a setting to (optionally) include the new Network Security Configuration file available in Android 7.x (Nougat) no any new APK that is rebuild through APK Studio (specially with a target SDK version of Android 7.x, or API level 24).

The new feature should allow adding a permissive default network_security_config.xml file that allows intercepting all HTTPS traffic generated by the app accepting both system and user imported CAs, o adding a custom XML file provided by the user.

See: https://developer.android.com/training/articles/security-config.html

Suggested default file for: res/xml/network_security_config.xml

```
<network-security-config>  
      <base-config>  
            <trust-anchors>  
                <!-- Trust system preinstalled CAs -->  
                <certificates src="system" />  
                <!-- Add trust for user imported CAs -->  
                <certificates src="user" />  
           </trust-anchors>  
      </base-config>  
 </network-security-config>
```

**Comment by vaibhavpandeyvpz** [comment]
I believe apktool should include it while rebuilding if you create one in *res/xml*. Did it work for you? I did not get what you wanted. You want a one-click action to create this file or an action to create new files in decompiled source?

**Comment by raulsiles** [comment]
Although apktool v2.2.1 has added support for Android 7.x (Nougat) I do not find any reference to adding the network_Security_config.xml file. My proposal for APK Studio is to include one in res/xml for apktool to use automatically, if the corresponding option is enabled on the user preferences. It can be the default file suggested above, or another one referenced by the user.

I was thinking about a configuration option (checkbox) that the user can select if he is interested on adding the default file (when the target SDK is API Level 24+), so APK Studio adds it to res/xml before building the new APK, plus another option with a file reference (text field with the file path) in case the user wants to add its own custom file (vs. the default one) to all APK Studio projects when building new APKs.

**Comment by raulsiles** [comment]
Simply rebuilding the app through apktool is not enough, even if the network_security_config.xml file has been added to "res/xml", as it also has to be referenced from the AndroidManifest.xml file:
```
<application ...
android:networkSecurityConfig="@xml/network_security_config">
```

These two steps could be accomplished by apktool itself (feature request: https://github.com/iBotPeaches/Apktool/issues/1622), or by APK Studio (if that apktool feature request is not finally implemented).

**Comment by vaibhavpandeyvpz** [comment]
Well I would refrain from doing things automagically that do not have to be universally applied. This can be easily achieved by placing a file in `res/xml`, modifying `AndroidManifest.xml` and rebuild. That's what [APK Studio](https://github.com/vaibhavpandeyvpz/apkstudio) is for.
