### ISSUE TITLE
Automatically set default project name and location based on APK path

### ISSUE THREAD

**Issue by JayXon** [vaibhavpandeyvpz/apkstudio#7]
For example, if I choose `D:\abc\1.apk`
The project name could be default to `1` and location could be `D:\abc\`

**Comment by vaibhavpandeyvpz** [comment]
@JayXon this has been implemented in recent version. It won't ask you now :+1:

**Comment by JayXon** [comment]
Thanks, it works great!
Another convenient feature would be support drag and drop. For example, if I drag an apk from file explorer to apkstudio, it should do the same as I choose open apk and then select that file.

**Comment by vaibhavpandeyvpz** [comment]
Added drag/drop support for APKs & supported text/image files to open for editing :smile: 89c91d83b4057418ee6349703c59cc32af5bf131

**Comment by JayXon** [comment]
Awesome, thank you.
