### ISSUE TITLE
thrid party files not found

### ISSUE THREAD

**Issue by WHK102** [vaibhavpandeyvpz/apkstudio#70]
When open the application says need vendor 3rd party apps and show this link: http://www.vaibhavpandey.com/apkstudio , but is broken :-/, now, when decompile apk says "Unable to access jarfile apktool.jar".

Howto download all required files?

**Comment by joadr** [comment]
The same thing happens to me :(

**Comment by vaibhavpandeyvpz** [comment]
Get them here: https://www.dropbox.com/s/gwsuf9lolvd3j37/vendor.zip?dl=0
