### ISSUE TITLE
Makefile:474: recipe for target 'adb.o' failed

### ISSUE THREAD

**Issue by rfrogman** [vaibhavpandeyvpz/apkstudio#73]
Having issue making application......
root@linux:~/Documents/apkstudio# make
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DAPP_REV_SHORT=\"9e114ca\" -DAPP_REV_LONG=\"9e114ca369602442bd0247d272ccdb40db9b0462\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o adb.o src/adb.cpp
In file included from ./include/adb.h:5:0,
                 from src/adb.cpp:1:
./include/process.h:4:30: fatal error: QRegularExpression: No such file or directory

                              ^
compilation terminated.
Makefile:474: recipe for target 'adb.o' failed
make: *** [adb.o] Error 1
root@linux:~/Documents/apkstudio# qmake -version
QMake version 3.0
Using Qt version 5.7.1 in /usr/lib/x86_64-linux-gnu

**Comment by Surendrajat** [comment]
Check #15
