### ISSUE TITLE
ERROR Could not find java.dll

### ISSUE THREAD

**Issue by AndriodappDeveloper** [vaibhavpandeyvpz/apkstudio#75]
Unable to decompile apk file from APK STUDIO
ERROR Could not find Java.dll

Note- i have attached screen shot below
![error](https://cloud.githubusercontent.com/assets/25612519/22693902/2a42da5e-ed6b-11e6-988a-fc7c2db8920c.png)

**Comment by Surendrajat** [comment]
Install **JAVA** again and check path variable.
