### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by JackLauu** [vaibhavpandeyvpz/apkstudio#8]
What about the idea of add dex2jar to apkstudio? Then it can also get the source.
I don't know why apktool can't directly get the source. I have completed the work,
if need to contribute.

**Comment by vaibhavpandeyvpz** [comment]
I do not know how good the contribution thing is there on Codeplex, but if it has been done then tell me your codeplex ID, I will add you to development team of the project so you push the code up there.

**Comment by vaibhavpandeyvpz** [comment]
@JackLauu I may add dex2jar in future if I am unable to find a on-deman/per-file smali2java converter in the while. I just don't want to add 30+ more seconds to the decompilation process. My earliest version has the functionality and the method was not reliable for larger applications.
