### ISSUE TITLE
Signing fails "Process exited with code -1"

### ISSUE THREAD

**Issue by kheush** [vaibhavpandeyvpz/apkstudio#80]
Hi,
This tool is great an very intuitive.
Still struggling however to build signed APK.
Some guidance would be much appreaciated.

1. Generated key tool and alia using keytool.
2. Then used Sign/Export. 
3. Entered keystore path, password, alias, and alias password (as specified during generation)

At validation, I get following error:
$ jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore "C:/Program Files/Java/jdk1.8.0_131/bin/debug.keystore" -storepass android -keypass android -signedjar C:/Users/DELL/AppData/Local/Temp/FRaqbC8w-signed.apk C:/Users/DELL/Documents/kheush/app-releases/Projects/com.zuulu.zuulu.apk androiddebugkey
Process exited with code -1

I have tried on 2 different versions of APK Studio: 0978cd4 and 0978cd4.

![image](https://cloud.githubusercontent.com/assets/10047202/26810204/c19a87ee-4a59-11e7-800b-671763889d2c.png)

**Comment by kheush** [comment]
Managed to find a way (requires third party tool):

Prerequisite: Build (unsigned) apk with APK Studio
1. Generate keytool, key and passphrase with keytool
keytool -genkey -v -keystore my-release-key.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000
2. Then sign application (built from APK Studio) with jarsigner
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my-release-key.keystore my_application.apk alias_name

**Comment by micahg** [comment]
This doesn't work for me anymore, i had to just omit the -sigalg as its not inferred from -digestalg (or so i read). Any chance this will get a fix?

**Comment by Surendrajat** [comment]
Latest version doesn't require keystore generation and import.
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
