### ISSUE TITLE
build does not generate the "built.apk" file

### ISSUE THREAD

**Issue by VapiSoft** [vaibhavpandeyvpz/apkstudio#82]
Thank you very much for the tool.
But when I tried the "build", it did not create the rebuilt.apk, although it writes in the console: building apk...
Any idea?
This is the console log:
`$ java -Xmx2048m -jar C:/Users/t410/.apkstudio/vendor/apktool.jar -f b C:/acr/base -o C:/acr/base.apk
I: Using Apktool 2.2.2
I: Smaling smali folder into classes.dex...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
Process exited with code 0
`

**Comment by Surendrajat** [comment]
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
