### ISSUE TITLE
Upgrading android resource framework for windows version

### ISSUE THREAD

**Issue by JustAKay** [vaibhavpandeyvpz/apkstudio#84]
Hi, I'm very new to this tool and trying to learn how to use it to its full potential for work. I started getting errors when decompiling recently that with some research lead me to the answer of needing to upgrade my android resource framework. However, I see nowhere to do that for the Windows version of APKstudio, in actuality I may just be completely missing it. I'm running Windows 10 x64, and APKStudio d49d3de. Any help would be greatly appreciated.

**Comment by Surendrajat** [comment]
After downloading `apktool` in desired folder, follow the guide [here](https://ibotpeaches.github.io/Apktool/documentation/#frameworks).
