### ISSUE TITLE
Included APKTool out of date

### ISSUE THREAD

**Issue by japzone1** [vaibhavpandeyvpz/apkstudio#87]
For those having build issues, most of them probably originate from the fact that the included APKTool is out of date. 

Fix:

1. Download latest APKTool from here: https://ibotpeaches.github.io/Apktool/
2. Copy the file to (On Windows): `C:\Users\USERNAME\.apkstudio\vendor\`
3. Delete the old `apktool.jar` and rename the new one to `apktool.jar`
4. Open the `VERSION` file with a text editor, and change the version number listed within to match the APKTool you just downloaded. Save the changes.

Done. Now just open APKStudio again to make sure no error windows popup, and then decompile/decode your APK again from scratch because the old APKTool might've screwed up when decompiling causing you issues later when trying to compile.

**Comment by Surendrajat** [comment]
Good. However now you can easily download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
