### ISSUE TITLE
APK studio seem like a virus

### ISSUE THREAD

**Issue by SrikanthSd** [vaibhavpandeyvpz/apkstudio#88]
Hey broh @vaibhavpandeyvpz 

When i install apkstudio in any directory,on launching it is just deleting all the contents in that directory.
Tried two times and happened the same.

please do reply

**Comment by VivekGadhvi** [comment]
Well. Apk studio ain't a virus.

**Comment by Surendrajat** [comment]
Never mind. Scan it with cool AV ;)
Latest builds are **portable** and doesn't need **installation** at all, if that's where something was wrong.
