### ISSUE TITLE
Third-party apps/files not available by default or in the suggested link

### ISSUE THREAD

**Issue by raulsiles** [vaibhavpandeyvpz/apkstudio#89]
After installing APK Studio under Windows, the first time it runs it displays an error message requesting additional third-party files:
![image](https://user-images.githubusercontent.com/5730357/30803847-75e426cc-a1eb-11e7-884c-aef4b88e49d1.png)

The link is not available (Server not found):
http://github.vaibhavpandey.com/apkstudio

I have tried both currently available builds, with the same date ( Nov 19, 2015 ) but with different size, and the result is the same for both (Why do they have a different size? Different version? Which file is the preferred one?):
https://bintray.com/vaibhavpandeyvpz/generic/apkstudio/view
https://bintray.com/vaibhavpandeyvpz/generic/apkstudio/d49d3de
https://bintray.com/vaibhavpandeyvpz/generic/apkstudio/0978cd4

It would be useful to provide details about the expected third-party files requested by APK Studio, as well as fixing the link so that the expected files are available.

After reading issue #87 and #66, it seems you only need to copy the latest version of "apktool.jar" to "C:\Users\USERNAME\\.apkstudio\vendor\" and create a "VERSION" file (text file, without any extension)  in that same folder, with the version number for apktool (Is this really required, or can this "VERSION" file be empty? Using a blank or empty "VERSION" file is mentioned by the author in issue #32).

As an extra step, verify under APK Studio - Edit - Settings that the "Vendor path" variable is pointing to "C:\Users\USERNAME\\.apkstudio\vendor\".

**Comment by baksosapi** [comment]
#66

**Comment by Surendrajat** [comment]
Download [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements).
