### ISSUE TITLE
google maps not working

### ISSUE THREAD

**Issue by catrucho** [vaibhavpandeyvpz/apkstudio#9]
Hello.
I have and apk that I decompiled propertly and I am able to make a small change, recompile and make it work.

The problem is that the apik uses google maps ( API I guess)

So when I recompiled everything is working except maps I guess is because of the apk signature on recompiling.

How can I make it work, signed or whatsoever to be able to make maps api working inside de apk?

Thanks a lot

**Comment by vaibhavpandeyvpz** [comment]
If it's with the signatures, then recompiling ain't going to fix it. You can't sign your APK with Google's cert (because you don't have the key).
