### ISSUE TITLE
Feature request: Improve APK Studio workflow in the GUI

### ISSUE THREAD

**Issue by raulsiles** [vaibhavpandeyvpz/apkstudio#90]
I would suggest the following improvements in the functionality and graphical user interface (GUI) of the tool to simplify and facilitate the standard APK Studio workflow:

Steps:
1. Open (target) APK or Directory
2. <Work on the project, edit the app and save the changes>
3. Build --> Add the option to make a copy of the original APK, (e.g.) by adding the ".original" extension, before overwriting the current APK file.
4. (NEW: Optional) Allow the user to generate the Android developer keystore (see issue #67)
5. Sign/Export (APK)
6. NEW: Uninstall (a previous version of the app) --> It is required to extract first the full package name for the app used by "adb uninstall ...".
7. Install (the new version of the app)

I would suggest providing quick shortcuts through the current tool icons toolbar for each of these steps, as well as through the "Project" menu. Some of these steps are missing in the current icon set displayed by the tool (in the icons toolbar; e.g. Install).

**Comment by Surendrajat** [comment]
#### Update:
>3. Fixed the original APK being overwritten. New APK will have `_mod` in its name.
>4. No need to generate keystore anymore. Thanks to `uber-apk-signer`
>6. Might come in future. (It's just one time process, not actually a part of workflow and then comes `adb install -r`)

And the `Install` Button is added in toolbar.
