### ISSUE TITLE
Feature request: Add an option to include the debuggable flag to the app manifest

### ISSUE THREAD

**Issue by raulsiles** [vaibhavpandeyvpz/apkstudio#91]
Similarly to issue #68, it would be very useful to have a setting to (optionally) include the "android:debuggable="true"" flag to the app AndroidManifext.xml file.

This setting could be available under Edit - Settings, or much better, could be set through a dialog window during the Project - Build process (in the same way the Project - Sign/Export process asks the user for the signing keys).

It could be implemented manually (modifying the AndroidManifext.xml file) or simply executed via the "apktool b -d" option, once the associated [iBotPeaches/Apktool/issues#1621](https://github.com/iBotPeaches/Apktool/issues/1621) is resolved.

**Comment by vaibhavpandeyvpz** [comment]
Better would be to wait for [apktool](https://github.com/iBotPeaches/Apktool/issues/1621) fix this and them delegate it to the [apktool](https://github.com/iBotPeaches/Apktool/).
