### ISSUE TITLE
"The process for the file protocol died unexpectedly."

### ISSUE THREAD

**Issue by sitanshuforever** [vaibhavpandeyvpz/apkstudio#93]
I am using KDE Plasma, Dolphin File manager. followed the same steps written in description:

![image](https://user-images.githubusercontent.com/2941024/31096513-e8e832f0-a7d9-11e7-9f8b-4e2c8b06ed17.png)

![image](https://user-images.githubusercontent.com/2941024/31096478-c671edd8-a7d9-11e7-9483-5be7a8c7e7b7.png)

**Comment by VivekGadhvi** [comment]
Delete /.kde as well as the /tmp/kde-user & /var/tmp/kdecache-user directories

**Comment by sitanshuforever** [comment]
still Not working.. :(

**Comment by Surendrajat** [comment]
Please try the [latest version](https://github.com/vaibhavpandeyvpz/apkstudio/releases) of APK Studio as its universal AppImage file and then follow [the instructions](https://github.com/vaibhavpandeyvpz/apkstudio#requirements). Let me know if the problem persists.
