### ISSUE TITLE
Error 3rd-party!

### ISSUE THREAD

**Issue by questionpython** [vaibhavpandeyvpz/apkstudio#95]
ERROR:
```
You need to download some 3rd-party applications/files from here and place them in /home/max/.apkstudio/vendor for APK Studio to work.
```

How can fix?
https://github.com/vaibhavpandeyvpz/apkstudio/issues/89

**Comment by questionpython** [comment]
@vaibhavpandeyvpz

**Comment by Surendrajat** [comment]
@questionpython have you solved your problem? If not read instructions [here](https://github.com/Surendrajat/ApkStudio#instructions).
