### ISSUE TITLE
use apksigner instead of jarsigner

### ISSUE THREAD

**Issue by kangzhay92** [vaibhavpandeyvpz/apkstudio#96]
apksigner is recommended tool now, jarsigner does not produce APK Signature Scheme v2 signatures introduced in Android Nougat, whereas apksigner does.

Maybe use this [https://github.com/patrickfav/uber-apk-signer](url), its supports v1 and v2 Android signing scheme.

**Comment by Surendrajat** [comment]
It's implemented in new release. Have a look [here](https://github.com/Surendrajat/ApkStudio/releases).
